// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

import 'package:dio/dio.dart';
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Service implementation for the `DELETE /notifications/{id}` API endpoint.
final class DeleteNotificationsById extends OpenApiService<void> {
  new({
    required this.id,
  });

  final String id;

  @override
  Dio get $dio => Api.dio;

  @override
  OpenApiMethod get $method => .delete;

  @override
  String get $url => '/notifications/${id.encodeUri()}';

  @override
  String toString() => 'DeleteNotificationsById(id: $id)';
}
