// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

import 'package:dio/dio.dart';
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Service implementation for the `DELETE /notifications` API endpoint.
final class DeleteNotifications extends OpenApiService<void> {
  @override
  Dio get $dio => Api.dio;

  @override
  OpenApiMethod get $method => .delete;

  @override
  String get $url => '/notifications';

  @override
  String toString() => 'DeleteNotifications()';
}
