// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

import 'package:dio/dio.dart';
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Service implementation for the `GET /me/followings` API endpoint.
final class GetMeFollowings extends OpenApiService<MyFollowingsResponse> {
  new({
    this.cursor,
    this.size,
    this.keyword,
  });

  final String? cursor;
  final num? size;
  final String? keyword;

  @override
  Dio get $dio => Api.dio;

  @override
  OpenApiMethod get $method => .get;

  @override
  String get $url => '/me/followings';

  @override
  Map<String, dynamic> get $query => {
    'cursor': cursor.encode(),
    'size': size.encode(),
    'keyword': keyword.encode(),
  };

  @override
  MyFollowingsResponse decode(Object? obj) {
    return obj.decode<MyFollowingsResponse>()!;
  }

  @override
  String toString() => 'GetMeFollowings(cursor: $cursor, size: $size, keyword: $keyword)';
}
