// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

import 'package:dio/dio.dart';
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Service implementation for the `GET /notifications` API endpoint.
final class GetNotifications extends OpenApiService<List<NotificationResponse>> {
  @override
  Dio get $dio => Api.dio;

  @override
  OpenApiMethod get $method => .get;

  @override
  String get $url => '/notifications';

  @override
  List<NotificationResponse> decode(Object? obj) {
    return obj.decode<List<NotificationResponse>>()!;
  }

  @override
  String toString() => 'GetNotifications()';
}
