// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

import 'package:dio/dio.dart';
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Service implementation for the `GET /feeds/search` API endpoint.
final class GetFeedsSearch extends OpenApiService<SearchedFeedsResponse> {
  new({
    this.cursor,
    this.size,
    required this.keyword,
    required this.sort,
  });

  final String? cursor;
  final num? size;
  final String keyword;
  final FeedSearchSort sort;

  @override
  Dio get $dio => Api.dio;

  @override
  OpenApiMethod get $method => .get;

  @override
  String get $url => '/feeds/search';

  @override
  Map<String, dynamic> get $query => {
    'cursor': cursor.encode(),
    'size': size.encode(),
    'keyword': keyword.encode(),
    'sort': sort.encode(),
  };

  @override
  SearchedFeedsResponse decode(Object? obj) {
    return obj.decode<SearchedFeedsResponse>()!;
  }
}
