// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

import 'package:dio/dio.dart';
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Service implementation for the `GET /me/blockings` API endpoint.
final class GetMeBlockings extends OpenApiService<MyBlockingsResponse> {
  @override
  Dio get $dio => Api.dio;

  @override
  OpenApiMethod get $method => .get;

  @override
  String get $url => '/me/blockings';

  @override
  MyBlockingsResponse decode(Object? obj) {
    return obj.decode<MyBlockingsResponse>()!;
  }

  @override
  String toString() => 'GetMeBlockings()';
}
