// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

import 'package:dio/dio.dart';
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Service implementation for the `GET /posts` API endpoint.
final class GetPosts extends OpenApiService<PostsResponse> {
  new({
    this.page,
    this.size,
    required this.type,
  });

  final num? page;
  final num? size;
  final PostTypeFilter type;

  @override
  Dio get $dio => Api.dio;

  @override
  OpenApiMethod get $method => .get;

  @override
  String get $url => '/posts';

  @override
  Map<String, dynamic> get $query => {
    'page': page.encode(),
    'size': size.encode(),
    'type': type.encode(),
  };

  @override
  PostsResponse decode(Object? obj) {
    return obj.decode<PostsResponse>()!;
  }

  @override
  String toString() => 'GetPosts(page: $page, size: $size, type: $type)';
}
