// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

import 'package:dio/dio.dart';
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Service implementation for the `GET /users/popular` API endpoint.
final class GetUsersPopular extends OpenApiService<List<PopularUserResponse>> {
  @override
  Dio get $dio => Api.dio;

  @override
  OpenApiMethod get $method => .get;

  @override
  String get $url => '/users/popular';

  @override
  List<PopularUserResponse> decode(Object? obj) {
    return obj.decode<List<PopularUserResponse>>()!;
  }
}
