// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

import 'package:dio/dio.dart';
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Service implementation for the `GET /feed-comments` API endpoint.
final class GetFeedComments extends OpenApiService<List<ParentFeedCommentResponse>> {
  new({
    required this.feedId,
  });

  final String feedId;

  @override
  Dio get $dio => Api.dio;

  @override
  OpenApiMethod get $method => .get;

  @override
  String get $url => '/feed-comments';

  @override
  Map<String, dynamic> get $query => {
    'feedId': feedId.encode(),
  };

  @override
  List<ParentFeedCommentResponse> decode(Object? obj) {
    return obj.decode<List<ParentFeedCommentResponse>>()!;
  }

  @override
  String toString() => 'GetFeedComments(feedId: $feedId)';
}
