// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

import 'package:dio/dio.dart';
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Service implementation for the `GET /tags/popular` API endpoint.
final class GetTagsPopular extends OpenApiService<List<PopularTagResponse>> {
  @override
  Dio get $dio => Api.dio;

  @override
  OpenApiMethod get $method => .get;

  @override
  String get $url => '/tags/popular';

  @override
  List<PopularTagResponse> decode(Object? obj) {
    return obj.decode<List<PopularTagResponse>>()!;
  }

  @override
  String toString() => 'GetTagsPopular()';
}
