// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

import 'package:dio/dio.dart';
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Service implementation for the `GET /users/search` API endpoint.
final class GetUsersSearch extends OpenApiService<SearchedUsersResponse> {
  new({
    this.cursor,
    this.size,
    required this.keyword,
  });

  final String? cursor;
  final num? size;
  final String keyword;

  @override
  Dio get $dio => Api.dio;

  @override
  OpenApiMethod get $method => .get;

  @override
  String get $url => '/users/search';

  @override
  Map<String, dynamic> get $query => {
    'cursor': cursor.encode(),
    'size': size.encode(),
    'keyword': keyword.encode(),
  };

  @override
  SearchedUsersResponse decode(Object? obj) {
    return obj.decode<SearchedUsersResponse>()!;
  }
}
