// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

import 'package:dio/dio.dart';
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Service implementation for the `GET /feeds/{id}/like` API endpoint.
final class GetFeedsByIdLike extends OpenApiService<List<FeedLikedUserResponse>> {
  new({
    required this.id,
  });

  final String id;

  @override
  Dio get $dio => Api.dio;

  @override
  OpenApiMethod get $method => .get;

  @override
  String get $url => '/feeds/${id.encodeUri()}/like';

  @override
  List<FeedLikedUserResponse> decode(Object? obj) {
    return obj.decode<List<FeedLikedUserResponse>>()!;
  }

  @override
  String toString() => 'GetFeedsByIdLike(id: $id)';
}
