// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

import 'package:dio/dio.dart';
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Service implementation for the `GET /health-check` API endpoint.
final class GetHealthCheck extends OpenApiService<String> {
  @override
  Dio get $dio => Api.dio;

  @override
  OpenApiMethod get $method => .get;

  @override
  String get $url => '/health-check';

  @override
  String decode(Object? obj) {
    return obj.decode<String>()!;
  }
}
