// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

import 'package:dio/dio.dart';
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Service implementation for the `GET /posts/notices` API endpoint.
final class GetPostsNotices extends OpenApiService<List<PostWithAuthorResponse>> {
  @override
  Dio get $dio => Api.dio;

  @override
  OpenApiMethod get $method => .get;

  @override
  String get $url => '/posts/notices';

  @override
  List<PostWithAuthorResponse> decode(Object? obj) {
    return obj.decode<List<PostWithAuthorResponse>>()!;
  }

  @override
  String toString() => 'GetPostsNotices()';
}
