// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

import 'package:dio/dio.dart';
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Service implementation for the `GET /feeds/latest` API endpoint.
final class GetFeedsLatest extends OpenApiService<LatestFeedsResponse> {
  new({
    this.cursor,
    this.size,
  });

  final String? cursor;
  final num? size;

  @override
  Dio get $dio => Api.dio;

  @override
  OpenApiMethod get $method => .get;

  @override
  String get $url => '/feeds/latest';

  @override
  Map<String, dynamic> get $query => {
    'cursor': cursor.encode(),
    'size': size.encode(),
  };

  @override
  LatestFeedsResponse decode(Object? obj) {
    return obj.decode<LatestFeedsResponse>()!;
  }
}
