// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

import 'package:dio/dio.dart';
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Service implementation for the `GET /post-comments` API endpoint.
final class GetPostComments extends OpenApiService<List<ParentPostCommentResponse>> {
  new({
    required this.postId,
  });

  final String postId;

  @override
  Dio get $dio => Api.dio;

  @override
  OpenApiMethod get $method => .get;

  @override
  String get $url => '/post-comments';

  @override
  Map<String, dynamic> get $query => {
    'postId': postId.encode(),
  };

  @override
  List<ParentPostCommentResponse> decode(Object? obj) {
    return obj.decode<List<ParentPostCommentResponse>>()!;
  }
}
