// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

import 'package:dio/dio.dart';
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Service implementation for the `GET /me/save-feeds` API endpoint.
final class GetMeSaveFeeds extends OpenApiService<MyLikeFeedsResponse> {
  new({
    this.cursor,
    this.size,
  });

  final String? cursor;
  final num? size;

  @override
  Dio get $dio => Api.dio;

  @override
  OpenApiMethod get $method => .get;

  @override
  String get $url => '/me/save-feeds';

  @override
  Map<String, dynamic> get $query => {
    'cursor': cursor.encode(),
    'size': size.encode(),
  };

  @override
  MyLikeFeedsResponse decode(Object? obj) {
    return obj.decode<MyLikeFeedsResponse>()!;
  }

  @override
  String toString() => 'GetMeSaveFeeds(cursor: $cursor, size: $size)';
}
