// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

import 'package:dio/dio.dart';
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Service implementation for the `GET /users/{id}/posts` API endpoint.
final class GetUsersByIdPosts extends OpenApiService<List<MyPostResponse>> {
  new({
    required this.id,
    this.page,
    this.size,
  });

  final String id;
  final num? page;
  final num? size;

  @override
  Dio get $dio => Api.dio;

  @override
  OpenApiMethod get $method => .get;

  @override
  String get $url => '/users/${id.encodeUri()}/posts';

  @override
  Map<String, dynamic> get $query => {
    'page': page.encode(),
    'size': size.encode(),
  };

  @override
  List<MyPostResponse> decode(Object? obj) {
    return obj.decode<List<MyPostResponse>>()!;
  }
}
