// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

import 'package:dio/dio.dart';
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Service implementation for the `GET /users/{id}` API endpoint.
final class GetUsersById extends OpenApiService<UserProfileResponse> {
  new({
    required this.id,
  });

  final String id;

  @override
  Dio get $dio => Api.dio;

  @override
  OpenApiMethod get $method => .get;

  @override
  String get $url => '/users/${id.encodeUri()}';

  @override
  UserProfileResponse decode(Object? obj) {
    return obj.decode<UserProfileResponse>()!;
  }

  @override
  String toString() => 'GetUsersById(id: $id)';
}
