// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

import 'package:dio/dio.dart';
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Service implementation for the `GET /me` API endpoint.
final class GetMe extends OpenApiService<MyProfileResponse> {
  @override
  Dio get $dio => Api.dio;

  @override
  OpenApiMethod get $method => .get;

  @override
  String get $url => '/me';

  @override
  MyProfileResponse decode(Object? obj) {
    return obj.decode<MyProfileResponse>()!;
  }
}
