// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

import 'package:dio/dio.dart';
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Service implementation for the `GET /chats/{id}/user` API endpoint.
final class GetChatsByIdUser extends OpenApiService<OpponentUserResponse> {
  new({
    required this.id,
  });

  final String id;

  @override
  Dio get $dio => Api.dio;

  @override
  OpenApiMethod get $method => .get;

  @override
  String get $url => '/chats/${id.encodeUri()}/user';

  @override
  OpponentUserResponse decode(Object? obj) {
    return obj.decode<OpponentUserResponse>()!;
  }
}
