// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

import 'package:dio/dio.dart';
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Service implementation for the `GET /me/save-posts` API endpoint.
final class GetMeSavePosts extends OpenApiService<MySavePostsResponse> {
  new({
    this.page,
    this.size,
  });

  final num? page;
  final num? size;

  @override
  Dio get $dio => Api.dio;

  @override
  OpenApiMethod get $method => .get;

  @override
  String get $url => '/me/save-posts';

  @override
  Map<String, dynamic> get $query => {
    'page': page.encode(),
    'size': size.encode(),
  };

  @override
  MySavePostsResponse decode(Object? obj) {
    return obj.decode<MySavePostsResponse>()!;
  }

  @override
  String toString() => 'GetMeSavePosts(page: $page, size: $size)';
}
