// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

import 'package:dio/dio.dart';
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Service implementation for the `GET /posts/{id}` API endpoint.
final class GetPostsById extends OpenApiService<PostDetailResponse> {
  new({
    required this.id,
  });

  final String id;

  @override
  Dio get $dio => Api.dio;

  @override
  OpenApiMethod get $method => .get;

  @override
  String get $url => '/posts/${id.encodeUri()}';

  @override
  PostDetailResponse decode(Object? obj) {
    return obj.decode<PostDetailResponse>()!;
  }

  @override
  String toString() => 'GetPostsById(id: $id)';
}
