// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

import 'package:dio/dio.dart';
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Service implementation for the `GET /chat-messages` API endpoint.
final class GetChatMessages extends OpenApiService<ChatMessagesResponse> {
  new({
    this.cursor,
    this.size,
    required this.chatId,
  });

  final String? cursor;
  final num? size;
  final String chatId;

  @override
  Dio get $dio => Api.dio;

  @override
  OpenApiMethod get $method => .get;

  @override
  String get $url => '/chat-messages';

  @override
  Map<String, dynamic> get $query => {
    'cursor': cursor.encode(),
    'size': size.encode(),
    'chatId': chatId.encode(),
  };

  @override
  ChatMessagesResponse decode(Object? obj) {
    return obj.decode<ChatMessagesResponse>()!;
  }

  @override
  String toString() => 'GetChatMessages(cursor: $cursor, size: $size, chatId: $chatId)';
}
