// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

import 'package:dio/dio.dart';
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Service implementation for the `GET /feeds/{id}` API endpoint.
final class GetFeedsById extends OpenApiService<FeedDetailResponse> {
  new({
    required this.id,
  });

  final String id;

  @override
  Dio get $dio => Api.dio;

  @override
  OpenApiMethod get $method => .get;

  @override
  String get $url => '/feeds/${id.encodeUri()}';

  @override
  FeedDetailResponse decode(Object? obj) {
    return obj.decode<FeedDetailResponse>()!;
  }

  @override
  String toString() => 'GetFeedsById(id: $id)';
}
