// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

import 'package:dio/dio.dart';
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Service implementation for the `PATCH /commission-works/{id}/complete` API endpoint.
final class PatchCommissionWorksByIdComplete extends OpenApiService<IdResponse> {
  new({
    required this.id,
  });

  final String id;

  @override
  Dio get $dio => Api.dio;

  @override
  OpenApiMethod get $method => .patch;

  @override
  String get $url => '/commission-works/${id.encodeUri()}/complete';

  @override
  IdResponse decode(Object? obj) {
    return obj.decode<IdResponse>()!;
  }

  @override
  String toString() => 'PatchCommissionWorksByIdComplete(id: $id)';
}
