// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

import 'package:dio/dio.dart';
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Service implementation for the `PATCH /albums/{id}` API endpoint.
final class PatchAlbumsById extends OpenApiService<void> {
  new({
    required this.id,
    required this._request,
  });

  final String id;
  final UpdateAlbumRequest _request;

  @override
  Dio get $dio => Api.dio;

  @override
  OpenApiMethod get $method => .patch;

  @override
  String get $url => '/albums/${id.encodeUri()}';

  @override
  String get $contentType => 'application/json';

  @override
  Object? get $body => _request.encode();

  @override
  String toString() => 'PatchAlbumsById(id: $id, _request: $_request)';
}
