// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

import 'package:dio/dio.dart';
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Service implementation for the `POST /feed-comments` API endpoint.
final class PostFeedComments extends OpenApiService<void> {
  new({
    required this._request,
  });

  final CreateFeedCommentRequest _request;

  @override
  Dio get $dio => Api.dio;

  @override
  OpenApiMethod get $method => .post;

  @override
  String get $url => '/feed-comments';

  @override
  String get $contentType => 'application/json';

  @override
  Object? get $body => _request.encode();
}
