// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

import 'package:dio/dio.dart';
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Service implementation for the `POST /albums` API endpoint.
final class PostAlbums extends OpenApiService<IdResponse> {
  new({
    required this._request,
  });

  final CreateAlbumRequest _request;

  @override
  Dio get $dio => Api.dio;

  @override
  OpenApiMethod get $method => .post;

  @override
  String get $url => '/albums';

  @override
  String get $contentType => 'application/json';

  @override
  Object? get $body => _request.encode();

  @override
  IdResponse decode(Object? obj) {
    return obj.decode<IdResponse>()!;
  }

  @override
  String toString() => 'PostAlbums(_request: $_request)';
}
