// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

import 'package:dio/dio.dart';
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Service implementation for the `POST /post-comments` API endpoint.
final class PostPostComments extends OpenApiService<IdResponse> {
  new({
    required this._request,
  });

  final CreatePostCommentRequest _request;

  @override
  Dio get $dio => Api.dio;

  @override
  OpenApiMethod get $method => .post;

  @override
  String get $url => '/post-comments';

  @override
  String get $contentType => 'application/json';

  @override
  Object? get $body => _request.encode();

  @override
  IdResponse decode(Object? obj) {
    return obj.decode<IdResponse>()!;
  }
}
