// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

import 'package:dio/dio.dart';
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Service implementation for the `POST /auth/logout` API endpoint.
final class PostAuthLogout extends OpenApiService<void> {
  new({
    this.grimityAppModel,
    this.grimityAppDevice,
  });

  final String? grimityAppModel;
  final String? grimityAppDevice;

  @override
  Dio get $dio => Api.dio;

  @override
  OpenApiMethod get $method => .post;

  @override
  String get $url => '/auth/logout';

  @override
  Map<String, dynamic> get $headers => {
    'grimity-app-model': grimityAppModel.encode(),
    'grimity-app-device': grimityAppDevice.encode(),
  };

  @override
  String toString() => 'PostAuthLogout(grimityAppModel: $grimityAppModel, grimityAppDevice: $grimityAppDevice)';
}
