// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

import 'package:dio/dio.dart';
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Service implementation for the `POST /commission-works/{id}/memos` API endpoint.
final class PostCommissionWorksByIdMemos extends OpenApiService<IdResponse> {
  new({
    required this.id,
    required this._request,
  });

  final String id;
  final CreateCommissionWorkMemoRequest _request;

  @override
  Dio get $dio => Api.dio;

  @override
  OpenApiMethod get $method => .post;

  @override
  String get $url => '/commission-works/${id.encodeUri()}/memos';

  @override
  String get $contentType => 'application/json';

  @override
  Object? get $body => _request.encode();

  @override
  IdResponse decode(Object? obj) {
    return obj.decode<IdResponse>()!;
  }

  @override
  String toString() => 'PostCommissionWorksByIdMemos(id: $id, _request: $_request)';
}
