// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

import 'package:dio/dio.dart';
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Service implementation for the `POST /reports` API endpoint.
final class PostReports extends OpenApiService<void> {
  new({
    required this._request,
  });

  final CreateReportRequest _request;

  @override
  Dio get $dio => Api.dio;

  @override
  OpenApiMethod get $method => .post;

  @override
  String get $url => '/reports';

  @override
  String get $contentType => 'application/json';

  @override
  Object? get $body => _request.encode();

  @override
  String toString() => 'PostReports(_request: $_request)';
}
