// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

import 'package:dio/dio.dart';
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Service implementation for the `PUT /feeds/{id}` API endpoint.
final class PutFeedsById extends OpenApiService<void> {
  new({
    required this.id,
    required this._request,
  });

  final String id;
  final UpdateFeedRequest _request;

  @override
  Dio get $dio => Api.dio;

  @override
  OpenApiMethod get $method => .put;

  @override
  String get $url => '/feeds/${id.encodeUri()}';

  @override
  String get $contentType => 'application/json';

  @override
  Object? get $body => _request.encode();
}
