// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

import 'package:dio/dio.dart';
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Service implementation for the `PUT /me/image` API endpoint.
final class PutMeImage extends OpenApiService<void> {
  new({
    required this._request,
  });

  final UpdateProfileImageRequest _request;

  @override
  Dio get $dio => Api.dio;

  @override
  OpenApiMethod get $method => .put;

  @override
  String get $url => '/me/image';

  @override
  String get $contentType => 'application/json';

  @override
  Object? get $body => _request.encode();

  @override
  String toString() => 'PutMeImage(_request: $_request)';
}
