// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

import 'package:dio/dio.dart';
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Service implementation for the `PUT /users/{id}/block` API endpoint.
final class PutUsersByIdBlock extends OpenApiService<void> {
  new({
    required this.id,
  });

  final String id;

  @override
  Dio get $dio => Api.dio;

  @override
  OpenApiMethod get $method => .put;

  @override
  String get $url => '/users/${id.encodeUri()}/block';

  @override
  String toString() => 'PutUsersByIdBlock(id: $id)';
}
