// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

import 'package:dio/dio.dart';
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Service implementation for the `PUT /users/{id}/follow` API endpoint.
final class PutUsersByIdFollow extends OpenApiService<void> {
  new({
    required this.id,
  });

  final String id;

  @override
  Dio get $dio => Api.dio;

  @override
  OpenApiMethod get $method => .put;

  @override
  String get $url => '/users/${id.encodeUri()}/follow';
}
