// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

import 'package:dio/dio.dart';
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Service implementation for the `PUT /me/commission-notice` API endpoint.
final class PutMeCommissionNotice extends OpenApiService<CommissionNoticeResponse> {
  new({
    required this._request,
  });

  final UpsertCommissionNoticeRequest _request;

  @override
  Dio get $dio => Api.dio;

  @override
  OpenApiMethod get $method => .put;

  @override
  String get $url => '/me/commission-notice';

  @override
  String get $contentType => 'application/json';

  @override
  Object? get $body => _request.encode();

  @override
  CommissionNoticeResponse decode(Object? obj) {
    return obj.decode<CommissionNoticeResponse>()!;
  }

  @override
  String toString() => 'PutMeCommissionNotice(_request: $_request)';
}
