// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

import 'package:dio/dio.dart';
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Service implementation for the `PUT /albums/order` API endpoint.
final class PutAlbumsOrder extends OpenApiService<void> {
  new({
    required this._request,
  });

  final UpdateAlbumOrderRequest _request;

  @override
  Dio get $dio => Api.dio;

  @override
  OpenApiMethod get $method => .put;

  @override
  String get $url => '/albums/order';

  @override
  String get $contentType => 'application/json';

  @override
  Object? get $body => _request.encode();
}
