// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

import 'package:dio/dio.dart';
import 'package:pervice_openapi/pervice_openapi.dart';

import 'api.dart';

export 'model/app_version_response.dart';
export 'enum/auth_provider.dart';
export 'model/login_request.dart';
export 'model/login_response.dart';
export 'model/register_request.dart';
export 'model/register409_response.dart';
export 'model/jwt_response.dart';
export 'model/check_name_request.dart';
export 'model/searched_user_response.dart';
export 'model/searched_users_response.dart';
export 'model/popular_user_response.dart';
export 'model/link_response.dart';
export 'model/album_with_count_response.dart';
export 'model/user_profile_response.dart';
export 'model/user_meta_response.dart';
export 'enum/user_feeds_sort.dart';
export 'model/user_feed_response.dart';
export 'model/user_feeds_response.dart';
export 'enum/post_type.dart';
export 'model/my_post_response.dart';
export 'model/commission_notice_base_response.dart';
export 'model/commission_notice_response.dart';
export 'enum/social_provider.dart';
export 'model/my_profile_response.dart';
export 'model/update_link_request.dart';
export 'model/update_user_request.dart';
export 'model/update_profile_conflict_response.dart';
export 'model/update_profile_image_request.dart';
export 'model/register_push_token_request.dart';
export 'model/update_background_image_request.dart';
export 'model/subscription_response.dart';
export 'enum/subscription_type.dart';
export 'model/update_subscription_request.dart';
export 'model/follower_user_response.dart';
export 'model/my_followers_response.dart';
export 'model/follow_user_response.dart';
export 'model/my_followings_response.dart';
export 'model/user_base_response.dart';
export 'model/my_blockings_response.dart';
export 'model/my_like_feed_response.dart';
export 'model/my_like_feeds_response.dart';
export 'model/post_with_author_response.dart';
export 'model/my_save_posts_response.dart';
export 'model/my_like_posts_response.dart';
export 'model/album_base_response.dart';
export 'model/verify_identity_request.dart';
export 'model/verify_identity409_response.dart';
export 'model/verify_identity422_response.dart';
export 'model/my_identity_verification_response.dart';
export 'model/upsert_commission_notice_request.dart';
export 'model/create_feed_request.dart';
export 'model/id_response.dart';
export 'model/delete_feeds_request.dart';
export 'enum/feed_search_sort.dart';
export 'model/searched_feed_response.dart';
export 'model/searched_feeds_response.dart';
export 'model/feed_ranking_response.dart';
export 'model/feed_rankings_response.dart';
export 'model/latest_feed_response.dart';
export 'model/latest_feeds_response.dart';
export 'model/feed_comment_with_writer_response.dart';
export 'model/following_feed_response.dart';
export 'model/following_feeds_response.dart';
export 'model/user_base_with_blocked_response.dart';
export 'model/feed_detail_response.dart';
export 'model/feed_meta_response.dart';
export 'model/update_feed_request.dart';
export 'model/feed_liked_user_response.dart';
export 'model/popular_tag_response.dart';
export 'model/create_post_request.dart';
export 'enum/post_type_filter.dart';
export 'model/posts_response.dart';
export 'enum/post_search_by.dart';
export 'model/post_detail_response.dart';
export 'model/post_base_response.dart';
export 'model/create_album_request.dart';
export 'model/update_album_order_request.dart';
export 'model/remove_feeds_album_request.dart';
export 'model/insert_feeds_request.dart';
export 'model/update_album_request.dart';
export 'model/create_feed_comment_request.dart';
export 'model/child_feed_comment_response.dart';
export 'model/parent_feed_comment_response.dart';
export 'model/notification_response.dart';
export 'model/create_post_comment_request.dart';
export 'model/child_post_comment_response.dart';
export 'model/parent_post_comment_response.dart';
export 'enum/report_type.dart';
export 'enum/report_ref_type.dart';
export 'model/create_report_request.dart';
export 'model/create_chat_request.dart';
export 'model/last_chat_message_response.dart';
export 'model/chat_response.dart';
export 'model/chats_response.dart';
export 'model/batch_delete_chats_request.dart';
export 'model/opponent_user_response.dart';
export 'model/join_chat_request.dart';
export 'model/leave_chat_request.dart';
export 'model/create_chat_message_request.dart';
export 'enum/chat_message_type.dart';
export 'model/reply_to_response.dart';
export 'model/chat_message_response.dart';
export 'model/chat_messages_response.dart';
export 'enum/image_type.dart';
export 'enum/image_ext.dart';
export 'model/get_image_upload_url_request.dart';
export 'model/image_upload_url_response.dart';
export 'enum/commission_question_type.dart';
export 'model/commission_question_item.dart';
export 'model/create_commission_request.dart';
export 'model/commission_answer_item.dart';
export 'model/create_commission_work_request.dart';
export 'model/create_commission_work400_response.dart';
export 'model/create_commission_work404_response.dart';
export 'model/accept_commission_work403_response.dart';
export 'model/accept_commission_work404_response.dart';
export 'model/accept_commission_work409_response.dart';
export 'model/cancel_commission_work403_response.dart';
export 'model/cancel_commission_work404_response.dart';
export 'model/cancel_commission_work409_response.dart';
export 'model/complete_commission_work403_response.dart';
export 'model/complete_commission_work404_response.dart';
export 'model/complete_commission_work409_response.dart';
export 'model/reject_commission_work_request.dart';
export 'model/reject_commission_work403_response.dart';
export 'model/reject_commission_work404_response.dart';
export 'model/reject_commission_work409_response.dart';
export 'model/upload_commission_work_result_request.dart';
export 'model/upload_commission_work_result403_response.dart';
export 'model/upload_commission_work_result404_response.dart';
export 'model/upload_commission_work_result409_response.dart';
export 'model/create_commission_work_memo_request.dart';
export 'model/create_commission_work_memo403_response.dart';
export 'model/create_commission_work_memo404_response.dart';
export 'model/create_commission_review_request.dart';
export 'model/create_commission_review403_response.dart';
export 'model/create_commission_review404_response.dart';
export 'model/create_commission_review409_response.dart';
export 'model/error_response.dart';
export 'service/get_health_check.dart';
export 'service/get_app_version.dart';
export 'service/post_auth_login.dart';
export 'service/post_auth_register.dart';
export 'service/get_auth_refresh.dart';
export 'service/post_auth_logout.dart';
export 'service/post_users_name_check.dart';
export 'service/get_users_search.dart';
export 'service/get_users_popular.dart';
export 'service/get_users_profile_by_url.dart';
export 'service/get_users_profile_by_url_meta.dart';
export 'service/get_users_by_id.dart';
export 'service/get_users_by_id_meta.dart';
export 'service/get_users_by_id_feeds.dart';
export 'service/get_users_by_id_posts.dart';
export 'service/get_users_by_id_commission_notice.dart';
export 'service/put_users_by_id_follow.dart';
export 'service/delete_users_by_id_follow.dart';
export 'service/put_users_by_id_block.dart';
export 'service/delete_users_by_id_block.dart';
export 'service/get_me.dart';
export 'service/put_me.dart';
export 'service/delete_me.dart';
export 'service/put_me_image.dart';
export 'service/delete_me_image.dart';
export 'service/put_me_push_token.dart';
export 'service/put_me_background.dart';
export 'service/delete_me_background.dart';
export 'service/get_me_subscribe.dart';
export 'service/put_me_subscribe.dart';
export 'service/get_me_followers.dart';
export 'service/get_me_followings.dart';
export 'service/get_me_blockings.dart';
export 'service/delete_me_followers_by_id.dart';
export 'service/get_me_like_feeds.dart';
export 'service/get_me_save_feeds.dart';
export 'service/get_me_save_posts.dart';
export 'service/get_me_like_posts.dart';
export 'service/get_me_albums.dart';
export 'service/get_me_identity_verification.dart';
export 'service/post_me_identity_verification.dart';
export 'service/get_me_commission_notice.dart';
export 'service/put_me_commission_notice.dart';
export 'service/delete_me_commission_notice.dart';
export 'service/post_feeds.dart';
export 'service/post_feeds_batch_delete.dart';
export 'service/get_feeds_search.dart';
export 'service/get_feeds_rankings.dart';
export 'service/get_feeds_latest.dart';
export 'service/get_feeds_following.dart';
export 'service/get_feeds_by_id.dart';
export 'service/put_feeds_by_id.dart';
export 'service/delete_feeds_by_id.dart';
export 'service/get_feeds_by_id_meta.dart';
export 'service/get_feeds_by_id_like.dart';
export 'service/put_feeds_by_id_like.dart';
export 'service/delete_feeds_by_id_like.dart';
export 'service/put_feeds_by_id_save.dart';
export 'service/delete_feeds_by_id_save.dart';
export 'service/put_feeds_by_id_view.dart';
export 'service/get_tags_popular.dart';
export 'service/get_posts.dart';
export 'service/post_posts.dart';
export 'service/get_posts_notices.dart';
export 'service/get_posts_search.dart';
export 'service/get_posts_by_id.dart';
export 'service/put_posts_by_id.dart';
export 'service/delete_posts_by_id.dart';
export 'service/get_posts_by_id_meta.dart';
export 'service/put_posts_by_id_like.dart';
export 'service/delete_posts_by_id_like.dart';
export 'service/put_posts_by_id_save.dart';
export 'service/delete_posts_by_id_save.dart';
export 'service/post_albums.dart';
export 'service/put_albums_order.dart';
export 'service/put_albums_null.dart';
export 'service/put_albums_by_id.dart';
export 'service/patch_albums_by_id.dart';
export 'service/delete_albums_by_id.dart';
export 'service/get_feed_comments.dart';
export 'service/post_feed_comments.dart';
export 'service/delete_feed_comments_by_id.dart';
export 'service/put_feed_comments_by_id_like.dart';
export 'service/delete_feed_comments_by_id_like.dart';
export 'service/get_notifications.dart';
export 'service/put_notifications.dart';
export 'service/delete_notifications.dart';
export 'service/put_notifications_by_id.dart';
export 'service/delete_notifications_by_id.dart';
export 'service/get_post_comments.dart';
export 'service/post_post_comments.dart';
export 'service/delete_post_comments_by_id.dart';
export 'service/put_post_comments_by_id_like.dart';
export 'service/delete_post_comments_by_id_like.dart';
export 'service/post_reports.dart';
export 'service/get_chats.dart';
export 'service/post_chats.dart';
export 'service/post_chats_batch_delete.dart';
export 'service/delete_chats_by_id.dart';
export 'service/get_chats_by_id_user.dart';
export 'service/put_chats_by_id_join.dart';
export 'service/put_chats_by_id_leave.dart';
export 'service/get_chat_messages.dart';
export 'service/post_chat_messages.dart';
export 'service/put_chat_messages_by_id_like.dart';
export 'service/delete_chat_messages_by_id_like.dart';
export 'service/post_images_get_upload_url.dart';
export 'service/post_images_get_upload_urls.dart';
export 'service/post_commissions.dart';
export 'service/put_commissions_by_id.dart';
export 'service/delete_commissions_by_id.dart';
export 'service/post_commission_works.dart';
export 'service/patch_commission_works_by_id_accept.dart';
export 'service/patch_commission_works_by_id_cancel.dart';
export 'service/patch_commission_works_by_id_complete.dart';
export 'service/patch_commission_works_by_id_reject.dart';
export 'service/put_commission_works_by_id_result.dart';
export 'service/post_commission_works_by_id_memos.dart';
export 'service/post_commission_works_by_id_reviews.dart';

/// Generated API configuration and codec registration.
abstract final class Api {
  /// Codecs registered by [setup].
  static const _codecs = <OpenApiCodec>[
    AppVersionResponse.codec,
    AuthProvider.codec,
    LoginRequest.codec,
    LoginResponse.codec,
    RegisterRequest.codec,
    Register409Response.codec,
    JwtResponse.codec,
    CheckNameRequest.codec,
    SearchedUserResponse.codec,
    SearchedUsersResponse.codec,
    PopularUserResponse.codec,
    LinkResponse.codec,
    AlbumWithCountResponse.codec,
    UserProfileResponse.codec,
    UserMetaResponse.codec,
    UserFeedsSort.codec,
    UserFeedResponse.codec,
    UserFeedsResponse.codec,
    PostType.codec,
    MyPostResponse.codec,
    CommissionNoticeBaseResponse.codec,
    CommissionNoticeResponse.codec,
    SocialProvider.codec,
    MyProfileResponse.codec,
    UpdateLinkRequest.codec,
    UpdateUserRequest.codec,
    UpdateProfileConflictResponse.codec,
    UpdateProfileImageRequest.codec,
    RegisterPushTokenRequest.codec,
    UpdateBackgroundImageRequest.codec,
    SubscriptionResponse.codec,
    SubscriptionType.codec,
    UpdateSubscriptionRequest.codec,
    FollowerUserResponse.codec,
    MyFollowersResponse.codec,
    FollowUserResponse.codec,
    MyFollowingsResponse.codec,
    UserBaseResponse.codec,
    MyBlockingsResponse.codec,
    MyLikeFeedResponse.codec,
    MyLikeFeedsResponse.codec,
    PostWithAuthorResponse.codec,
    MySavePostsResponse.codec,
    MyLikePostsResponse.codec,
    AlbumBaseResponse.codec,
    VerifyIdentityRequest.codec,
    VerifyIdentity409Response.codec,
    VerifyIdentity422Response.codec,
    MyIdentityVerificationResponse.codec,
    UpsertCommissionNoticeRequest.codec,
    CreateFeedRequest.codec,
    IdResponse.codec,
    DeleteFeedsRequest.codec,
    FeedSearchSort.codec,
    SearchedFeedResponse.codec,
    SearchedFeedsResponse.codec,
    FeedRankingResponse.codec,
    FeedRankingsResponse.codec,
    LatestFeedResponse.codec,
    LatestFeedsResponse.codec,
    FeedCommentWithWriterResponse.codec,
    FollowingFeedResponse.codec,
    FollowingFeedsResponse.codec,
    UserBaseWithBlockedResponse.codec,
    FeedDetailResponse.codec,
    FeedMetaResponse.codec,
    UpdateFeedRequest.codec,
    FeedLikedUserResponse.codec,
    PopularTagResponse.codec,
    CreatePostRequest.codec,
    PostTypeFilter.codec,
    PostsResponse.codec,
    PostSearchBy.codec,
    PostDetailResponse.codec,
    PostBaseResponse.codec,
    CreateAlbumRequest.codec,
    UpdateAlbumOrderRequest.codec,
    RemoveFeedsAlbumRequest.codec,
    InsertFeedsRequest.codec,
    UpdateAlbumRequest.codec,
    CreateFeedCommentRequest.codec,
    ChildFeedCommentResponse.codec,
    ParentFeedCommentResponse.codec,
    NotificationResponse.codec,
    CreatePostCommentRequest.codec,
    ChildPostCommentResponse.codec,
    ParentPostCommentResponse.codec,
    ReportType.codec,
    ReportRefType.codec,
    CreateReportRequest.codec,
    CreateChatRequest.codec,
    LastChatMessageResponse.codec,
    ChatResponse.codec,
    ChatsResponse.codec,
    BatchDeleteChatsRequest.codec,
    OpponentUserResponse.codec,
    JoinChatRequest.codec,
    LeaveChatRequest.codec,
    CreateChatMessageRequest.codec,
    ChatMessageType.codec,
    ReplyToResponse.codec,
    ChatMessageResponse.codec,
    ChatMessagesResponse.codec,
    ImageType.codec,
    ImageExt.codec,
    GetImageUploadUrlRequest.codec,
    ImageUploadUrlResponse.codec,
    CommissionQuestionType.codec,
    CommissionQuestionItem.codec,
    CreateCommissionRequest.codec,
    CommissionAnswerItem.codec,
    CreateCommissionWorkRequest.codec,
    CreateCommissionWork400Response.codec,
    CreateCommissionWork404Response.codec,
    AcceptCommissionWork403Response.codec,
    AcceptCommissionWork404Response.codec,
    AcceptCommissionWork409Response.codec,
    CancelCommissionWork403Response.codec,
    CancelCommissionWork404Response.codec,
    CancelCommissionWork409Response.codec,
    CompleteCommissionWork403Response.codec,
    CompleteCommissionWork404Response.codec,
    CompleteCommissionWork409Response.codec,
    RejectCommissionWorkRequest.codec,
    RejectCommissionWork403Response.codec,
    RejectCommissionWork404Response.codec,
    RejectCommissionWork409Response.codec,
    UploadCommissionWorkResultRequest.codec,
    UploadCommissionWorkResult403Response.codec,
    UploadCommissionWorkResult404Response.codec,
    UploadCommissionWorkResult409Response.codec,
    CreateCommissionWorkMemoRequest.codec,
    CreateCommissionWorkMemo403Response.codec,
    CreateCommissionWorkMemo404Response.codec,
    CreateCommissionReviewRequest.codec,
    CreateCommissionReview403Response.codec,
    CreateCommissionReview404Response.codec,
    CreateCommissionReview409Response.codec,
    ErrorResponse.codec,
  ];

  /// Dio instance configured by [setup].
  static Dio? _dio;

  /// HTTP client used by the generated services.
  static Dio get dio {
    assert(_dio != null, 'Api.setup(dio) must be called before use.');
    return _dio!;
  }

  /// Configures the HTTP client and registers the generated codecs.
  static void setup(Dio dio) {
    for (final codec in _codecs) {
      codec.register();
    }

    _dio = dio;
  }
}
