include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - 'lib/data/gen/**'
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
  errors:
    invalid_annotation_target: ignore
    deprecated_member_use: ignore
    deprecated_member_use_from_same_package: ignore

plugins:
  riverpod_lint: ^3.1.0

formatter:
  page_width: 120
  trailing_commas: preserve
