include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
  errors:
    invalid_annotation_target: ignore
    deprecated_member_use: ignore
    deprecated_member_use_from_same_package: ignore
  plugins:
    - custom_lint

formatter:
  page_width: 120
