include: package:flutter_lints/flutter.yaml

plugins:
  # 그리미티 디자인 시스템
  gds_lints:
    git:
      url: https://github.com/Grimity/gds-flutter.git
      path: packages/gds_lints

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**

formatter:
  page_width: 120
  trailing_commas: preserve
