name: grimity
description: 그림쟁이들을 위한 그림 커뮤니티, 그리미티에 대한 Flutter 기반의 모바일 애플리케이션입니다.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.13.5

dependencies:
  flutter:
    sdk: flutter
  pervice: ^1.1.0
  dio: ^5.11.1
  flutter_secure_storage: ^11.2.0
  flutter_cached_transition: ^1.0.1+1
  device_info_plus: ^13.3.0
  firebase_core: ^4.15.0
  animations: ^2.2.0
  git_config: ^1.1.0
  dotenv: ^4.2.0
  intl: ^0.20.3
  dynamic_height_list_view: ^0.0.2

  # 소셜 로그인
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^8.1.0
  kakao_flutter_sdk_user: ^2.0.1

  pervice_openapi:
    git:
      url: https://github.com/pervice-sdk/pervice-openapi

  # 그리미티 디자인 시스템
  gds_flutter:
    path: d:\Project Files\gds-flutter\packages\gds_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
