import 'package:grimity/app/di/di_setup.dart';
import 'package:grimity/domain/usecase/users/follow_user_usecase.dart';
import 'package:grimity/domain/usecase/users/name_check_usecase.dart';
import 'package:grimity/domain/usecase/users/search_user_usecase.dart';
import 'package:grimity/domain/usecase/users/get_popular_users_usecase.dart';
import 'package:grimity/domain/usecase/users/get_user_profile_usecase.dart';
import 'package:grimity/domain/usecase/users/get_user_meta_usecase.dart';
import 'package:grimity/domain/usecase/users/get_user_feeds_usecase.dart';
import 'package:grimity/domain/usecase/users/get_user_posts_usecase.dart';
import 'package:grimity/domain/usecase/users/unfollow_user_usecase.dart';

final nameCheckUseCase = getIt<NameCheckUseCase>();
final searchUserUseCase = getIt<SearchUserUseCase>();
final getPopularUsersUseCase = getIt<GetPopularUsersUseCase>();
final getUserProfileByUrlUseCase = getIt<GetUserProfileByUrlUseCase>();
final getUserProfileByIdUseCase = getIt<GetUserProfileByIdUseCase>();
final getUserMetaByUrlUseCase = getIt<GetUserMetaByUrlUseCase>();
final getUserMetaByIdUseCase = getIt<GetUserMetaByIdUseCase>();
final getUserFeedsUseCase = getIt<GetUserFeedsUseCase>();
final getUserPostsUseCase = getIt<GetUserPostsUseCase>();
final followUserByIdUseCase = getIt<FollowUserByIdUseCase>();
final unfollowUserByIdUseCase = getIt<UnfollowUserByIdUseCase>();