// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

import 'package:pervice_openapi/pervice_openapi.dart';

/// Enum representing the allowed values of AuthProvider.
enum AuthProvider {
  google('GOOGLE'),
  kakao('KAKAO'),
  apple('APPLE');

  const new(this.key);

  /// String key corresponding to the [AuthProvider].
  final String key;

  /// OpenAPI codec for encoding and decoding [AuthProvider].
  static const codec = _Codec();

  @override
  String toString() => 'AuthProvider.$key';
}

/// OpenAPI codec converting between the enum and its string key.
class _Codec extends OpenApiCodec<AuthProvider, String> {
  const new();

  @override
  AuthProvider decode(String key) => switch (key) {
    'GOOGLE' => .google,
    'KAKAO' => .kakao,
    'APPLE' => .apple,
    _ => throw FormatException('Invalid AuthProvider key: $key'),
  };

  @override
  String encode(AuthProvider value) => value.key;
}
