// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

import 'package:pervice_openapi/pervice_openapi.dart';

/// Enum representing the allowed values of ChatMessageType.
enum ChatMessageType {
  user('USER'),
  commissionRequested('COMMISSION_REQUESTED'),
  commissionAccepted('COMMISSION_ACCEPTED'),
  commissionRejected('COMMISSION_REJECTED'),
  commissionCanceled('COMMISSION_CANCELED'),
  commissionResultUploaded('COMMISSION_RESULT_UPLOADED'),
  commissionFinalUploaded('COMMISSION_FINAL_UPLOADED'),
  commissionCompleted('COMMISSION_COMPLETED');

  const new(this.key);

  /// String key corresponding to the [ChatMessageType].
  final String key;

  /// OpenAPI codec for encoding and decoding [ChatMessageType].
  static const codec = _Codec();
}

/// OpenAPI codec converting between the enum and its string key.
class _Codec extends OpenApiCodec<ChatMessageType, String> {
  const new();

  @override
  ChatMessageType decode(String key) => switch (key) {
    'USER' => .user,
    'COMMISSION_REQUESTED' => .commissionRequested,
    'COMMISSION_ACCEPTED' => .commissionAccepted,
    'COMMISSION_REJECTED' => .commissionRejected,
    'COMMISSION_CANCELED' => .commissionCanceled,
    'COMMISSION_RESULT_UPLOADED' => .commissionResultUploaded,
    'COMMISSION_FINAL_UPLOADED' => .commissionFinalUploaded,
    'COMMISSION_COMPLETED' => .commissionCompleted,
    _ => throw FormatException('Invalid ChatMessageType key: $key'),
  };

  @override
  String encode(ChatMessageType value) => value.key;
}
