// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

import 'package:pervice_openapi/pervice_openapi.dart';

/// Enum representing the allowed values of CommissionQuestionType.
enum CommissionQuestionType {
  text('TEXT'),
  singleSelect('SINGLE_SELECT'),
  multiSelect('MULTI_SELECT');

  const new(this.key);

  /// String key corresponding to the [CommissionQuestionType].
  final String key;

  /// OpenAPI codec for encoding and decoding [CommissionQuestionType].
  static const codec = _Codec();
}

/// OpenAPI codec converting between the enum and its string key.
class _Codec extends OpenApiCodec<CommissionQuestionType, String> {
  const new();

  @override
  CommissionQuestionType decode(String key) => switch (key) {
    'TEXT' => .text,
    'SINGLE_SELECT' => .singleSelect,
    'MULTI_SELECT' => .multiSelect,
    _ => throw FormatException('Invalid CommissionQuestionType key: $key'),
  };

  @override
  String encode(CommissionQuestionType value) => value.key;
}
