// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

import 'package:pervice_openapi/pervice_openapi.dart';

/// Enum representing the allowed values of FeedSearchSort.
enum FeedSearchSort {
  latest('latest'),
  popular('popular');

  const new(this.key);

  /// String key corresponding to the [FeedSearchSort].
  final String key;

  /// OpenAPI codec for encoding and decoding [FeedSearchSort].
  static const codec = _Codec();
}

/// OpenAPI codec converting between the enum and its string key.
class _Codec extends OpenApiCodec<FeedSearchSort, String> {
  const new();

  @override
  FeedSearchSort decode(String key) => switch (key) {
    'latest' => .latest,
    'popular' => .popular,
    _ => throw FormatException('Invalid FeedSearchSort key: $key'),
  };

  @override
  String encode(FeedSearchSort value) => value.key;
}
