// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

import 'package:pervice_openapi/pervice_openapi.dart';

/// Enum representing the allowed values of ImageExt.
enum ImageExt {
  webp('webp');

  const new(this.key);

  /// String key corresponding to the [ImageExt].
  final String key;

  /// OpenAPI codec for encoding and decoding [ImageExt].
  static const codec = _Codec();

  @override
  String toString() => 'ImageExt.$key';
}

/// OpenAPI codec converting between the enum and its string key.
class _Codec extends OpenApiCodec<ImageExt, String> {
  const new();

  @override
  ImageExt decode(String key) => switch (key) {
    'webp' => .webp,
    _ => throw FormatException('Invalid ImageExt key: $key'),
  };

  @override
  String encode(ImageExt value) => value.key;
}
