// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

import 'package:pervice_openapi/pervice_openapi.dart';

/// Enum representing the allowed values of ImageType.
enum ImageType {
  profile('profile'),
  feed('feed'),
  background('background'),
  post('post'),
  chat('chat'),
  commission('commission'),
  commissionReference('commission-reference'),
  commissionAnswer('commission-answer'),
  commissionWork('commission-work');

  const new(this.key);

  /// String key corresponding to the [ImageType].
  final String key;

  /// OpenAPI codec for encoding and decoding [ImageType].
  static const codec = _Codec();
}

/// OpenAPI codec converting between the enum and its string key.
class _Codec extends OpenApiCodec<ImageType, String> {
  const new();

  @override
  ImageType decode(String key) => switch (key) {
    'profile' => .profile,
    'feed' => .feed,
    'background' => .background,
    'post' => .post,
    'chat' => .chat,
    'commission' => .commission,
    'commission-reference' => .commissionReference,
    'commission-answer' => .commissionAnswer,
    'commission-work' => .commissionWork,
    _ => throw FormatException('Invalid ImageType key: $key'),
  };

  @override
  String encode(ImageType value) => value.key;
}
