// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

import 'package:pervice_openapi/pervice_openapi.dart';

/// Enum representing the allowed values of PostSearchBy.
enum PostSearchBy {
  combined('combined'),
  name('name');

  const new(this.key);

  /// String key corresponding to the [PostSearchBy].
  final String key;

  /// OpenAPI codec for encoding and decoding [PostSearchBy].
  static const codec = _Codec();
}

/// OpenAPI codec converting between the enum and its string key.
class _Codec extends OpenApiCodec<PostSearchBy, String> {
  const new();

  @override
  PostSearchBy decode(String key) => switch (key) {
    'combined' => .combined,
    'name' => .name,
    _ => throw FormatException('Invalid PostSearchBy key: $key'),
  };

  @override
  String encode(PostSearchBy value) => value.key;
}
