// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

import 'package:pervice_openapi/pervice_openapi.dart';

/// Enum representing the allowed values of PostTypeFilter.
enum PostTypeFilter {
  normal('NORMAL'),
  question('QUESTION'),
  feedback('FEEDBACK'),
  notice('NOTICE'),
  all('ALL');

  const new(this.key);

  /// String key corresponding to the [PostTypeFilter].
  final String key;

  /// OpenAPI codec for encoding and decoding [PostTypeFilter].
  static const codec = _Codec();

  @override
  String toString() => 'PostTypeFilter.$key';
}

/// OpenAPI codec converting between the enum and its string key.
class _Codec extends OpenApiCodec<PostTypeFilter, String> {
  const new();

  @override
  PostTypeFilter decode(String key) => switch (key) {
    'NORMAL' => .normal,
    'QUESTION' => .question,
    'FEEDBACK' => .feedback,
    'NOTICE' => .notice,
    'ALL' => .all,
    _ => throw FormatException('Invalid PostTypeFilter key: $key'),
  };

  @override
  String encode(PostTypeFilter value) => value.key;
}
