// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

import 'package:pervice_openapi/pervice_openapi.dart';

/// Enum representing the allowed values of PostType.
enum PostType {
  normal('NORMAL'),
  question('QUESTION'),
  feedback('FEEDBACK'),
  notice('NOTICE');

  const new(this.key);

  /// String key corresponding to the [PostType].
  final String key;

  /// OpenAPI codec for encoding and decoding [PostType].
  static const codec = _Codec();
}

/// OpenAPI codec converting between the enum and its string key.
class _Codec extends OpenApiCodec<PostType, String> {
  const new();

  @override
  PostType decode(String key) => switch (key) {
    'NORMAL' => .normal,
    'QUESTION' => .question,
    'FEEDBACK' => .feedback,
    'NOTICE' => .notice,
    _ => throw FormatException('Invalid PostType key: $key'),
  };

  @override
  String encode(PostType value) => value.key;
}
