// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

import 'package:pervice_openapi/pervice_openapi.dart';

/// Enum representing the allowed values of ReportRefType.
enum ReportRefType {
  user('USER'),
  feed('FEED'),
  feedComment('FEED_COMMENT'),
  post('POST'),
  postComment('POST_COMMENT'),
  chat('CHAT');

  const new(this.key);

  /// String key corresponding to the [ReportRefType].
  final String key;

  /// OpenAPI codec for encoding and decoding [ReportRefType].
  static const codec = _Codec();

  @override
  String toString() => 'ReportRefType.$key';
}

/// OpenAPI codec converting between the enum and its string key.
class _Codec extends OpenApiCodec<ReportRefType, String> {
  const new();

  @override
  ReportRefType decode(String key) => switch (key) {
    'USER' => .user,
    'FEED' => .feed,
    'FEED_COMMENT' => .feedComment,
    'POST' => .post,
    'POST_COMMENT' => .postComment,
    'CHAT' => .chat,
    _ => throw FormatException('Invalid ReportRefType key: $key'),
  };

  @override
  String encode(ReportRefType value) => value.key;
}
