// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

import 'package:pervice_openapi/pervice_openapi.dart';

/// Enum representing the allowed values of ReportType.
enum ReportType {
  case1('사칭계정'),
  case2('스팸/도배'),
  case3('욕설/비방'),
  case4('부적절한 프로필'),
  case5('선정적인 컨텐츠'),
  case6('기타');

  const new(this.key);

  /// String key corresponding to the [ReportType].
  final String key;

  /// OpenAPI codec for encoding and decoding [ReportType].
  static const codec = _Codec();
}

/// OpenAPI codec converting between the enum and its string key.
class _Codec extends OpenApiCodec<ReportType, String> {
  const new();

  @override
  ReportType decode(String key) => switch (key) {
    '사칭계정' => .case1,
    '스팸/도배' => .case2,
    '욕설/비방' => .case3,
    '부적절한 프로필' => .case4,
    '선정적인 컨텐츠' => .case5,
    '기타' => .case6,
    _ => throw FormatException('Invalid ReportType key: $key'),
  };

  @override
  String encode(ReportType value) => value.key;
}
