// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

import 'package:pervice_openapi/pervice_openapi.dart';

/// Enum representing the allowed values of SocialProvider.
enum SocialProvider {
  kakao('KAKAO'),
  google('GOOGLE');

  const new(this.key);

  /// String key corresponding to the [SocialProvider].
  final String key;

  /// OpenAPI codec for encoding and decoding [SocialProvider].
  static const codec = _Codec();
}

/// OpenAPI codec converting between the enum and its string key.
class _Codec extends OpenApiCodec<SocialProvider, String> {
  const new();

  @override
  SocialProvider decode(String key) => switch (key) {
    'KAKAO' => .kakao,
    'GOOGLE' => .google,
    _ => throw FormatException('Invalid SocialProvider key: $key'),
  };

  @override
  String encode(SocialProvider value) => value.key;
}
