// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

import 'package:pervice_openapi/pervice_openapi.dart';

/// Enum representing the allowed values of SubscriptionType.
enum SubscriptionType {
  follow('FOLLOW'),
  feedLike('FEED_LIKE'),
  feedComment('FEED_COMMENT'),
  feedReply('FEED_REPLY'),
  postComment('POST_COMMENT'),
  postReply('POST_REPLY');

  const new(this.key);

  /// String key corresponding to the [SubscriptionType].
  final String key;

  /// OpenAPI codec for encoding and decoding [SubscriptionType].
  static const codec = _Codec();
}

/// OpenAPI codec converting between the enum and its string key.
class _Codec extends OpenApiCodec<SubscriptionType, String> {
  const new();

  @override
  SubscriptionType decode(String key) => switch (key) {
    'FOLLOW' => .follow,
    'FEED_LIKE' => .feedLike,
    'FEED_COMMENT' => .feedComment,
    'FEED_REPLY' => .feedReply,
    'POST_COMMENT' => .postComment,
    'POST_REPLY' => .postReply,
    _ => throw FormatException('Invalid SubscriptionType key: $key'),
  };

  @override
  String encode(SubscriptionType value) => value.key;
}
