// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

import 'package:pervice_openapi/pervice_openapi.dart';

/// Enum representing the allowed values of UserFeedsSort.
enum UserFeedsSort {
  latest('latest'),
  like('like'),
  oldest('oldest');

  const new(this.key);

  /// String key corresponding to the [UserFeedsSort].
  final String key;

  /// OpenAPI codec for encoding and decoding [UserFeedsSort].
  static const codec = _Codec();
}

/// OpenAPI codec converting between the enum and its string key.
class _Codec extends OpenApiCodec<UserFeedsSort, String> {
  const new();

  @override
  UserFeedsSort decode(String key) => switch (key) {
    'latest' => .latest,
    'like' => .like,
    'oldest' => .oldest,
    _ => throw FormatException('Invalid UserFeedsSort key: $key'),
  };

  @override
  String encode(UserFeedsSort value) => value.key;
}
