// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the AlbumBaseResponse schema.
final class AlbumBaseResponse {
  const new({
    required this.id,
    required this.name,
  });

  final String id;
  final String name;

  /// OpenAPI codec for encoding and decoding [AlbumBaseResponse].
  static const codec = _Codec();
}

/// OpenAPI codec converting between [AlbumBaseResponse] and a JSON object.
class _Codec extends OpenApiCodec<AlbumBaseResponse, Map<String, dynamic>> {
  const new();

  @override
  AlbumBaseResponse decode(Map<String, dynamic> obj) => .new(
    id: obj.decode<String>('id')!,
    name: obj.decode<String>('name')!,
  );

  @override
  Map<String, dynamic> encode(AlbumBaseResponse value) => {
    'id': value.id.encode(),
    'name': value.name.encode(),
  };
}
