// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the AlbumWithCountResponse schema.
final class AlbumWithCountResponse {
  const new({
    required this.id,
    required this.name,
    required this.feedCount,
  });

  final String id;
  final String name;
  final num feedCount;

  /// OpenAPI codec for encoding and decoding [AlbumWithCountResponse].
  static const codec = _Codec();
}

/// OpenAPI codec converting between [AlbumWithCountResponse] and a JSON object.
class _Codec extends OpenApiCodec<AlbumWithCountResponse, Map<String, dynamic>> {
  const new();

  @override
  AlbumWithCountResponse decode(Map<String, dynamic> obj) => .new(
    id: obj.decode<String>('id')!,
    name: obj.decode<String>('name')!,
    feedCount: obj.decode<num>('feedCount')!,
  );

  @override
  Map<String, dynamic> encode(AlbumWithCountResponse value) => {
    'id': value.id.encode(),
    'name': value.name.encode(),
    'feedCount': value.feedCount.encode(),
  };
}
