// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the AppVersionResponse schema.
final class AppVersionResponse {
  const new({
    required this.version,
    required this.createdAt,
  });

  final String version;
  final DateTime createdAt;

  /// OpenAPI codec for encoding and decoding [AppVersionResponse].
  static const codec = _Codec();

  @override
  String toString() => 'AppVersionResponse(version: $version, createdAt: $createdAt)';
}

/// OpenAPI codec converting between [AppVersionResponse] and a JSON object.
class _Codec extends OpenApiCodec<AppVersionResponse, Map<String, dynamic>> {
  const new();

  @override
  AppVersionResponse decode(Map<String, dynamic> obj) => .new(
    version: obj.decode<String>('version')!,
    createdAt: obj.decode<DateTime>('createdAt')!,
  );

  @override
  Map<String, dynamic> encode(AppVersionResponse value) => {
    'version': value.version.encode(),
    'createdAt': value.createdAt.encode(),
  };
}
