// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the BatchDeleteChatsRequest schema.
final class BatchDeleteChatsRequest {
  const new({
    required this.ids,
  });

  final List<String> ids;

  /// OpenAPI codec for encoding and decoding [BatchDeleteChatsRequest].
  static const codec = _Codec();

  @override
  String toString() => 'BatchDeleteChatsRequest(ids: $ids)';
}

/// OpenAPI codec converting between [BatchDeleteChatsRequest] and a JSON object.
class _Codec extends OpenApiCodec<BatchDeleteChatsRequest, Map<String, dynamic>> {
  const new();

  @override
  BatchDeleteChatsRequest decode(Map<String, dynamic> obj) => .new(
    ids: obj.decode<List<String>>('ids')!,
  );

  @override
  Map<String, dynamic> encode(BatchDeleteChatsRequest value) => {
    'ids': value.ids.encode(),
  };
}
