// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the ChatResponse schema.
final class ChatResponse {
  const new({
    required this.id,
    required this.unreadCount,
    required this.enteredAt,
    required this.opponentUser,
    this.lastMessage,
  });

  final String id;
  final num unreadCount;
  final DateTime enteredAt;
  final UserBaseResponse opponentUser;
  final LastChatMessageResponse? lastMessage;

  /// OpenAPI codec for encoding and decoding [ChatResponse].
  static const codec = _Codec();

  @override
  String toString() =>
      'ChatResponse(id: $id, unreadCount: $unreadCount, enteredAt: $enteredAt, opponentUser: $opponentUser, lastMessage: $lastMessage)';
}

/// OpenAPI codec converting between [ChatResponse] and a JSON object.
class _Codec extends OpenApiCodec<ChatResponse, Map<String, dynamic>> {
  const new();

  @override
  ChatResponse decode(Map<String, dynamic> obj) => .new(
    id: obj.decode<String>('id')!,
    unreadCount: obj.decode<num>('unreadCount')!,
    enteredAt: obj.decode<DateTime>('enteredAt')!,
    opponentUser: obj.decode<UserBaseResponse>('opponentUser')!,
    lastMessage: obj.decode<LastChatMessageResponse>('lastMessage'),
  );

  @override
  Map<String, dynamic> encode(ChatResponse value) => {
    'id': value.id.encode(),
    'unreadCount': value.unreadCount.encode(),
    'enteredAt': value.enteredAt.encode(),
    'opponentUser': value.opponentUser.encode(),
    'lastMessage': value.lastMessage?.encode(),
  };
}
