// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the ChatsResponse schema.
final class ChatsResponse {
  const new({
    this.nextCursor,
    required this.chats,
  });

  final String? nextCursor;
  final List<ChatResponse> chats;

  /// OpenAPI codec for encoding and decoding [ChatsResponse].
  static const codec = _Codec();

  @override
  String toString() => 'ChatsResponse(nextCursor: $nextCursor, chats: $chats)';
}

/// OpenAPI codec converting between [ChatsResponse] and a JSON object.
class _Codec extends OpenApiCodec<ChatsResponse, Map<String, dynamic>> {
  const new();

  @override
  ChatsResponse decode(Map<String, dynamic> obj) => .new(
    nextCursor: obj.decode<String>('nextCursor'),
    chats: obj.decode<List<ChatResponse>>('chats')!,
  );

  @override
  Map<String, dynamic> encode(ChatsResponse value) => {
    'nextCursor': value.nextCursor?.encode(),
    'chats': value.chats.encode(),
  };
}
