// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the ChatMessageResponse schema.
final class ChatMessageResponse {
  const new({
    required this.id,
    this.content,
    this.image,
    required this.images,
    required this.createdAt,
    required this.user,
    required this.isLike,
    required this.type,
    this.referenceId,
    this.replyTo,
  });

  final String id;
  final String? content;
  final String? image;
  final List<String> images;
  final DateTime createdAt;
  final UserBaseResponse user;
  final bool isLike;
  final ChatMessageType type;
  final String? referenceId;
  final ReplyToResponse? replyTo;

  /// OpenAPI codec for encoding and decoding [ChatMessageResponse].
  static const codec = _Codec();

  @override
  String toString() =>
      'ChatMessageResponse(id: $id, content: $content, image: $image, images: $images, createdAt: $createdAt, user: $user, isLike: $isLike, type: $type, referenceId: $referenceId, replyTo: $replyTo)';
}

/// OpenAPI codec converting between [ChatMessageResponse] and a JSON object.
class _Codec extends OpenApiCodec<ChatMessageResponse, Map<String, dynamic>> {
  const new();

  @override
  ChatMessageResponse decode(Map<String, dynamic> obj) => .new(
    id: obj.decode<String>('id')!,
    content: obj.decode<String>('content'),
    image: obj.decode<String>('image'),
    images: obj.decode<List<String>>('images')!,
    createdAt: obj.decode<DateTime>('createdAt')!,
    user: obj.decode<UserBaseResponse>('user')!,
    isLike: obj.decode<bool>('isLike')!,
    type: obj.decode<ChatMessageType>('type')!,
    referenceId: obj.decode<String>('referenceId'),
    replyTo: obj.decode<ReplyToResponse>('replyTo'),
  );

  @override
  Map<String, dynamic> encode(ChatMessageResponse value) => {
    'id': value.id.encode(),
    'content': value.content?.encode(),
    'image': value.image?.encode(),
    'images': value.images.encode(),
    'createdAt': value.createdAt.encode(),
    'user': value.user.encode(),
    'isLike': value.isLike.encode(),
    'type': value.type.encode(),
    'referenceId': value.referenceId?.encode(),
    'replyTo': value.replyTo?.encode(),
  };
}
