// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the ChatMessagesResponse schema.
final class ChatMessagesResponse {
  const new({
    this.nextCursor,
    required this.messages,
  });

  final String? nextCursor;
  final List<ChatMessageResponse> messages;

  /// OpenAPI codec for encoding and decoding [ChatMessagesResponse].
  static const codec = _Codec();

  @override
  String toString() => 'ChatMessagesResponse(nextCursor: $nextCursor, messages: $messages)';
}

/// OpenAPI codec converting between [ChatMessagesResponse] and a JSON object.
class _Codec extends OpenApiCodec<ChatMessagesResponse, Map<String, dynamic>> {
  const new();

  @override
  ChatMessagesResponse decode(Map<String, dynamic> obj) => .new(
    nextCursor: obj.decode<String>('nextCursor'),
    messages: obj.decode<List<ChatMessageResponse>>('messages')!,
  );

  @override
  Map<String, dynamic> encode(ChatMessagesResponse value) => {
    'nextCursor': value.nextCursor?.encode(),
    'messages': value.messages.encode(),
  };
}
