// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the CheckNameRequest schema.
final class CheckNameRequest {
  const new({
    required this.name,
  });

  final String name;

  /// OpenAPI codec for encoding and decoding [CheckNameRequest].
  static const codec = _Codec();

  @override
  String toString() => 'CheckNameRequest(name: $name)';
}

/// OpenAPI codec converting between [CheckNameRequest] and a JSON object.
class _Codec extends OpenApiCodec<CheckNameRequest, Map<String, dynamic>> {
  const new();

  @override
  CheckNameRequest decode(Map<String, dynamic> obj) => .new(
    name: obj.decode<String>('name')!,
  );

  @override
  Map<String, dynamic> encode(CheckNameRequest value) => {
    'name': value.name.encode(),
  };
}
