// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the ChildFeedCommentResponse schema.
final class ChildFeedCommentResponse {
  const new({
    required this.id,
    required this.content,
    required this.createdAt,
    required this.likeCount,
    required this.writer,
    this.mentionedUser,
    required this.isLike,
  });

  final String id;
  final String content;
  final DateTime createdAt;
  final num likeCount;
  final UserBaseResponse writer;
  final UserBaseResponse? mentionedUser;
  final bool isLike;

  /// OpenAPI codec for encoding and decoding [ChildFeedCommentResponse].
  static const codec = _Codec();

  @override
  String toString() =>
      'ChildFeedCommentResponse(id: $id, content: $content, createdAt: $createdAt, likeCount: $likeCount, writer: $writer, mentionedUser: $mentionedUser, isLike: $isLike)';
}

/// OpenAPI codec converting between [ChildFeedCommentResponse] and a JSON object.
class _Codec extends OpenApiCodec<ChildFeedCommentResponse, Map<String, dynamic>> {
  const new();

  @override
  ChildFeedCommentResponse decode(Map<String, dynamic> obj) => .new(
    id: obj.decode<String>('id')!,
    content: obj.decode<String>('content')!,
    createdAt: obj.decode<DateTime>('createdAt')!,
    likeCount: obj.decode<num>('likeCount')!,
    writer: obj.decode<UserBaseResponse>('writer')!,
    mentionedUser: obj.decode<UserBaseResponse>('mentionedUser'),
    isLike: obj.decode<bool>('isLike')!,
  );

  @override
  Map<String, dynamic> encode(ChildFeedCommentResponse value) => {
    'id': value.id.encode(),
    'content': value.content.encode(),
    'createdAt': value.createdAt.encode(),
    'likeCount': value.likeCount.encode(),
    'writer': value.writer.encode(),
    'mentionedUser': value.mentionedUser?.encode(),
    'isLike': value.isLike.encode(),
  };
}
