// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the ChildPostCommentResponse schema.
final class ChildPostCommentResponse {
  const new({
    required this.id,
    required this.content,
    required this.createdAt,
    required this.likeCount,
    required this.isLike,
    this.writer,
    this.mentionedUser,
  });

  final String id;
  final String content;
  final DateTime createdAt;
  final num likeCount;
  final bool isLike;
  final UserBaseResponse? writer;
  final UserBaseResponse? mentionedUser;

  /// OpenAPI codec for encoding and decoding [ChildPostCommentResponse].
  static const codec = _Codec();

  @override
  String toString() =>
      'ChildPostCommentResponse(id: $id, content: $content, createdAt: $createdAt, likeCount: $likeCount, isLike: $isLike, writer: $writer, mentionedUser: $mentionedUser)';
}

/// OpenAPI codec converting between [ChildPostCommentResponse] and a JSON object.
class _Codec extends OpenApiCodec<ChildPostCommentResponse, Map<String, dynamic>> {
  const new();

  @override
  ChildPostCommentResponse decode(Map<String, dynamic> obj) => .new(
    id: obj.decode<String>('id')!,
    content: obj.decode<String>('content')!,
    createdAt: obj.decode<DateTime>('createdAt')!,
    likeCount: obj.decode<num>('likeCount')!,
    isLike: obj.decode<bool>('isLike')!,
    writer: obj.decode<UserBaseResponse>('writer'),
    mentionedUser: obj.decode<UserBaseResponse>('mentionedUser'),
  );

  @override
  Map<String, dynamic> encode(ChildPostCommentResponse value) => {
    'id': value.id.encode(),
    'content': value.content.encode(),
    'createdAt': value.createdAt.encode(),
    'likeCount': value.likeCount.encode(),
    'isLike': value.isLike.encode(),
    'writer': value.writer?.encode(),
    'mentionedUser': value.mentionedUser?.encode(),
  };
}
