// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the CommissionNoticeResponse schema.
final class CommissionNoticeResponse {
  const new({
    this.notice,
  });

  final CommissionNoticeBaseResponse? notice;

  /// OpenAPI codec for encoding and decoding [CommissionNoticeResponse].
  static const codec = _Codec();
}

/// OpenAPI codec converting between [CommissionNoticeResponse] and a JSON object.
class _Codec extends OpenApiCodec<CommissionNoticeResponse, Map<String, dynamic>> {
  const new();

  @override
  CommissionNoticeResponse decode(Map<String, dynamic> obj) => .new(
    notice: obj.decode<CommissionNoticeBaseResponse>('notice'),
  );

  @override
  Map<String, dynamic> encode(CommissionNoticeResponse value) => {
    'notice': value.notice?.encode(),
  };
}
