// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the CommissionAnswerItem schema.
final class CommissionAnswerItem {
  const new({
    this.type,
    this.title,
    this.description,
    this.isRequired,
    this.options,
    this.text,
    this.selectedOptions,
    this.attachedImages,
  });

  final String? type;
  final String? title;
  final Map<String, dynamic>? description;
  final bool? isRequired;
  final List<String>? options;
  final Map<String, dynamic>? text;
  final List<String>? selectedOptions;
  final List<String>? attachedImages;

  /// OpenAPI codec for encoding and decoding [CommissionAnswerItem].
  static const codec = _Codec();

  @override
  String toString() =>
      'CommissionAnswerItem(type: $type, title: $title, description: $description, isRequired: $isRequired, options: $options, text: $text, selectedOptions: $selectedOptions, attachedImages: $attachedImages)';
}

/// OpenAPI codec converting between [CommissionAnswerItem] and a JSON object.
class _Codec extends OpenApiCodec<CommissionAnswerItem, Map<String, dynamic>> {
  const new();

  @override
  CommissionAnswerItem decode(Map<String, dynamic> obj) => .new(
    type: obj.decode<String>('type'),
    title: obj.decode<String>('title'),
    description: obj.decode<Map<String, dynamic>>('description'),
    isRequired: obj.decode<bool>('isRequired'),
    options: obj.decode<List<String>>('options'),
    text: obj.decode<Map<String, dynamic>>('text'),
    selectedOptions: obj.decode<List<String>>('selectedOptions'),
    attachedImages: obj.decode<List<String>>('attachedImages'),
  );

  @override
  Map<String, dynamic> encode(CommissionAnswerItem value) => {
    'type': value.type?.encode(),
    'title': value.title?.encode(),
    'description': value.description?.encode(),
    'isRequired': value.isRequired?.encode(),
    'options': value.options?.encode(),
    'text': value.text?.encode(),
    'selectedOptions': value.selectedOptions?.encode(),
    'attachedImages': value.attachedImages?.encode(),
  };
}
