// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the CommissionNoticeBaseResponse schema.
final class CommissionNoticeBaseResponse {
  const new({
    required this.title,
    required this.content,
    required this.updatedAt,
  });

  final String title;
  final String content;
  final DateTime updatedAt;

  /// OpenAPI codec for encoding and decoding [CommissionNoticeBaseResponse].
  static const codec = _Codec();
}

/// OpenAPI codec converting between [CommissionNoticeBaseResponse] and a JSON object.
class _Codec extends OpenApiCodec<CommissionNoticeBaseResponse, Map<String, dynamic>> {
  const new();

  @override
  CommissionNoticeBaseResponse decode(Map<String, dynamic> obj) => .new(
    title: obj.decode<String>('title')!,
    content: obj.decode<String>('content')!,
    updatedAt: obj.decode<DateTime>('updatedAt')!,
  );

  @override
  Map<String, dynamic> encode(CommissionNoticeBaseResponse value) => {
    'title': value.title.encode(),
    'content': value.content.encode(),
    'updatedAt': value.updatedAt.encode(),
  };
}
