// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the CommissionQuestionItem schema.
final class CommissionQuestionItem {
  const new({
    required this.type,
    required this.title,
    this.description,
    required this.isRequired,
    required this.options,
  });

  final CommissionQuestionType type;
  final String title;
  final Map<String, dynamic>? description;
  final bool isRequired;
  final List<String> options;

  /// OpenAPI codec for encoding and decoding [CommissionQuestionItem].
  static const codec = _Codec();
}

/// OpenAPI codec converting between [CommissionQuestionItem] and a JSON object.
class _Codec extends OpenApiCodec<CommissionQuestionItem, Map<String, dynamic>> {
  const new();

  @override
  CommissionQuestionItem decode(Map<String, dynamic> obj) => .new(
    type: obj.decode<CommissionQuestionType>('type')!,
    title: obj.decode<String>('title')!,
    description: obj.decode<Map<String, dynamic>>('description'),
    isRequired: obj.decode<bool>('isRequired')!,
    options: obj.decode<List<String>>('options')!,
  );

  @override
  Map<String, dynamic> encode(CommissionQuestionItem value) => {
    'type': value.type.encode(),
    'title': value.title.encode(),
    'description': value.description?.encode(),
    'isRequired': value.isRequired.encode(),
    'options': value.options.encode(),
  };
}
