// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the CreateFeedCommentRequest schema.
final class CreateFeedCommentRequest {
  const new({
    required this.feedId,
    this.parentCommentId,
    required this.content,
    this.mentionedUserId,
  });

  final String feedId;
  final String? parentCommentId;
  final String content;
  final String? mentionedUserId;

  /// OpenAPI codec for encoding and decoding [CreateFeedCommentRequest].
  static const codec = _Codec();

  @override
  String toString() =>
      'CreateFeedCommentRequest(feedId: $feedId, parentCommentId: $parentCommentId, content: $content, mentionedUserId: $mentionedUserId)';
}

/// OpenAPI codec converting between [CreateFeedCommentRequest] and a JSON object.
class _Codec extends OpenApiCodec<CreateFeedCommentRequest, Map<String, dynamic>> {
  const new();

  @override
  CreateFeedCommentRequest decode(Map<String, dynamic> obj) => .new(
    feedId: obj.decode<String>('feedId')!,
    parentCommentId: obj.decode<String>('parentCommentId'),
    content: obj.decode<String>('content')!,
    mentionedUserId: obj.decode<String>('mentionedUserId'),
  );

  @override
  Map<String, dynamic> encode(CreateFeedCommentRequest value) => {
    'feedId': value.feedId.encode(),
    'parentCommentId': value.parentCommentId?.encode(),
    'content': value.content.encode(),
    'mentionedUserId': value.mentionedUserId?.encode(),
  };
}
