// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the CreateChatRequest schema.
final class CreateChatRequest {
  const new({
    required this.targetUserId,
  });

  final String targetUserId;

  /// OpenAPI codec for encoding and decoding [CreateChatRequest].
  static const codec = _Codec();
}

/// OpenAPI codec converting between [CreateChatRequest] and a JSON object.
class _Codec extends OpenApiCodec<CreateChatRequest, Map<String, dynamic>> {
  const new();

  @override
  CreateChatRequest decode(Map<String, dynamic> obj) => .new(
    targetUserId: obj.decode<String>('targetUserId')!,
  );

  @override
  Map<String, dynamic> encode(CreateChatRequest value) => {
    'targetUserId': value.targetUserId.encode(),
  };
}
