// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the CreatePostCommentRequest schema.
final class CreatePostCommentRequest {
  const new({
    required this.postId,
    this.parentCommentId,
    required this.content,
    this.mentionedUserId,
  });

  final String postId;
  final String? parentCommentId;
  final String content;
  final String? mentionedUserId;

  /// OpenAPI codec for encoding and decoding [CreatePostCommentRequest].
  static const codec = _Codec();
}

/// OpenAPI codec converting between [CreatePostCommentRequest] and a JSON object.
class _Codec extends OpenApiCodec<CreatePostCommentRequest, Map<String, dynamic>> {
  const new();

  @override
  CreatePostCommentRequest decode(Map<String, dynamic> obj) => .new(
    postId: obj.decode<String>('postId')!,
    parentCommentId: obj.decode<String>('parentCommentId'),
    content: obj.decode<String>('content')!,
    mentionedUserId: obj.decode<String>('mentionedUserId'),
  );

  @override
  Map<String, dynamic> encode(CreatePostCommentRequest value) => {
    'postId': value.postId.encode(),
    'parentCommentId': value.parentCommentId?.encode(),
    'content': value.content.encode(),
    'mentionedUserId': value.mentionedUserId?.encode(),
  };
}
