// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the CreatePostRequest schema.
final class CreatePostRequest {
  const new({
    required this.title,
    required this.content,
    required this.type,
  });

  final String title;
  final String content;
  final PostType type;

  /// OpenAPI codec for encoding and decoding [CreatePostRequest].
  static const codec = _Codec();
}

/// OpenAPI codec converting between [CreatePostRequest] and a JSON object.
class _Codec extends OpenApiCodec<CreatePostRequest, Map<String, dynamic>> {
  const new();

  @override
  CreatePostRequest decode(Map<String, dynamic> obj) => .new(
    title: obj.decode<String>('title')!,
    content: obj.decode<String>('content')!,
    type: obj.decode<PostType>('type')!,
  );

  @override
  Map<String, dynamic> encode(CreatePostRequest value) => {
    'title': value.title.encode(),
    'content': value.content.encode(),
    'type': value.type.encode(),
  };
}
