// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the CreateCommissionWorkMemoRequest schema.
final class CreateCommissionWorkMemoRequest {
  const new({
    required this.content,
  });

  final String content;

  /// OpenAPI codec for encoding and decoding [CreateCommissionWorkMemoRequest].
  static const codec = _Codec();

  @override
  String toString() => 'CreateCommissionWorkMemoRequest(content: $content)';
}

/// OpenAPI codec converting between [CreateCommissionWorkMemoRequest] and a JSON object.
class _Codec extends OpenApiCodec<CreateCommissionWorkMemoRequest, Map<String, dynamic>> {
  const new();

  @override
  CreateCommissionWorkMemoRequest decode(Map<String, dynamic> obj) => .new(
    content: obj.decode<String>('content')!,
  );

  @override
  Map<String, dynamic> encode(CreateCommissionWorkMemoRequest value) => {
    'content': value.content.encode(),
  };
}
