// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the CreateAlbumRequest schema.
final class CreateAlbumRequest {
  const new({
    required this.name,
  });

  final String name;

  /// OpenAPI codec for encoding and decoding [CreateAlbumRequest].
  static const codec = _Codec();
}

/// OpenAPI codec converting between [CreateAlbumRequest] and a JSON object.
class _Codec extends OpenApiCodec<CreateAlbumRequest, Map<String, dynamic>> {
  const new();

  @override
  CreateAlbumRequest decode(Map<String, dynamic> obj) => .new(
    name: obj.decode<String>('name')!,
  );

  @override
  Map<String, dynamic> encode(CreateAlbumRequest value) => {
    'name': value.name.encode(),
  };
}
