// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the CreateCommissionRequest schema.
final class CreateCommissionRequest {
  const new({
    required this.title,
    required this.description,
    this.additionalCondition,
    required this.price,
    required this.workDays,
    required this.revisionCount,
    required this.images,
    required this.thumbnail,
    required this.tags,
    required this.questions,
    required this.isPublic,
  });

  final String title;
  final String description;
  final String? additionalCondition;
  final num price;
  final num workDays;
  final num revisionCount;
  final List<String> images;
  final String thumbnail;
  final List<String> tags;
  final List<CommissionQuestionItem> questions;
  final bool isPublic;

  /// OpenAPI codec for encoding and decoding [CreateCommissionRequest].
  static const codec = _Codec();

  @override
  String toString() =>
      'CreateCommissionRequest(title: $title, description: $description, additionalCondition: $additionalCondition, price: $price, workDays: $workDays, revisionCount: $revisionCount, images: $images, thumbnail: $thumbnail, tags: $tags, questions: $questions, isPublic: $isPublic)';
}

/// OpenAPI codec converting between [CreateCommissionRequest] and a JSON object.
class _Codec extends OpenApiCodec<CreateCommissionRequest, Map<String, dynamic>> {
  const new();

  @override
  CreateCommissionRequest decode(Map<String, dynamic> obj) => .new(
    title: obj.decode<String>('title')!,
    description: obj.decode<String>('description')!,
    additionalCondition: obj.decode<String>('additionalCondition'),
    price: obj.decode<num>('price')!,
    workDays: obj.decode<num>('workDays')!,
    revisionCount: obj.decode<num>('revisionCount')!,
    images: obj.decode<List<String>>('images')!,
    thumbnail: obj.decode<String>('thumbnail')!,
    tags: obj.decode<List<String>>('tags')!,
    questions: obj.decode<List<CommissionQuestionItem>>('questions')!,
    isPublic: obj.decode<bool>('isPublic')!,
  );

  @override
  Map<String, dynamic> encode(CreateCommissionRequest value) => {
    'title': value.title.encode(),
    'description': value.description.encode(),
    'additionalCondition': value.additionalCondition?.encode(),
    'price': value.price.encode(),
    'workDays': value.workDays.encode(),
    'revisionCount': value.revisionCount.encode(),
    'images': value.images.encode(),
    'thumbnail': value.thumbnail.encode(),
    'tags': value.tags.encode(),
    'questions': value.questions.encode(),
    'isPublic': value.isPublic.encode(),
  };
}
