// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the CreateCommissionReview403Response schema.
final class CreateCommissionReview403Response {
  const new({
    required this.status,
    required this.errorCode,
  });

  final num status;
  final String errorCode;

  /// OpenAPI codec for encoding and decoding [CreateCommissionReview403Response].
  static const codec = _Codec();

  @override
  String toString() => 'CreateCommissionReview403Response(status: $status, errorCode: $errorCode)';
}

/// OpenAPI codec converting between [CreateCommissionReview403Response] and a JSON object.
class _Codec extends OpenApiCodec<CreateCommissionReview403Response, Map<String, dynamic>> {
  const new();

  @override
  CreateCommissionReview403Response decode(Map<String, dynamic> obj) => .new(
    status: obj.decode<num>('status')!,
    errorCode: obj.decode<String>('errorCode')!,
  );

  @override
  Map<String, dynamic> encode(CreateCommissionReview403Response value) => {
    'status': value.status.encode(),
    'errorCode': value.errorCode.encode(),
  };
}
