// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the CreateCommissionWorkRequest schema.
final class CreateCommissionWorkRequest {
  const new({
    required this.authorId,
    required this.referenceImages,
    this.commissionId,
    this.answers,
  });

  final String authorId;
  final List<String> referenceImages;
  final Map<String, dynamic>? commissionId;
  final List<CommissionAnswerItem>? answers;

  /// OpenAPI codec for encoding and decoding [CreateCommissionWorkRequest].
  static const codec = _Codec();

  @override
  String toString() =>
      'CreateCommissionWorkRequest(authorId: $authorId, referenceImages: $referenceImages, commissionId: $commissionId, answers: $answers)';
}

/// OpenAPI codec converting between [CreateCommissionWorkRequest] and a JSON object.
class _Codec extends OpenApiCodec<CreateCommissionWorkRequest, Map<String, dynamic>> {
  const new();

  @override
  CreateCommissionWorkRequest decode(Map<String, dynamic> obj) => .new(
    authorId: obj.decode<String>('authorId')!,
    referenceImages: obj.decode<List<String>>('referenceImages')!,
    commissionId: obj.decode<Map<String, dynamic>>('commissionId'),
    answers: obj.decode<List<CommissionAnswerItem>>('answers'),
  );

  @override
  Map<String, dynamic> encode(CreateCommissionWorkRequest value) => {
    'authorId': value.authorId.encode(),
    'referenceImages': value.referenceImages.encode(),
    'commissionId': value.commissionId?.encode(),
    'answers': value.answers?.encode(),
  };
}
