// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the CreateCommissionReviewRequest schema.
final class CreateCommissionReviewRequest {
  const new({
    required this.rating,
    this.content,
  });

  final String rating;
  final Map<String, dynamic>? content;

  /// OpenAPI codec for encoding and decoding [CreateCommissionReviewRequest].
  static const codec = _Codec();
}

/// OpenAPI codec converting between [CreateCommissionReviewRequest] and a JSON object.
class _Codec extends OpenApiCodec<CreateCommissionReviewRequest, Map<String, dynamic>> {
  const new();

  @override
  CreateCommissionReviewRequest decode(Map<String, dynamic> obj) => .new(
    rating: obj.decode<String>('rating')!,
    content: obj.decode<Map<String, dynamic>>('content'),
  );

  @override
  Map<String, dynamic> encode(CreateCommissionReviewRequest value) => {
    'rating': value.rating.encode(),
    'content': value.content?.encode(),
  };
}
