// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the CreateChatMessageRequest schema.
final class CreateChatMessageRequest {
  const new({
    required this.chatId,
    this.content,
    required this.images,
    this.replyToId,
  });

  final String chatId;
  final String? content;
  final List<String> images;
  final String? replyToId;

  /// OpenAPI codec for encoding and decoding [CreateChatMessageRequest].
  static const codec = _Codec();

  @override
  String toString() =>
      'CreateChatMessageRequest(chatId: $chatId, content: $content, images: $images, replyToId: $replyToId)';
}

/// OpenAPI codec converting between [CreateChatMessageRequest] and a JSON object.
class _Codec extends OpenApiCodec<CreateChatMessageRequest, Map<String, dynamic>> {
  const new();

  @override
  CreateChatMessageRequest decode(Map<String, dynamic> obj) => .new(
    chatId: obj.decode<String>('chatId')!,
    content: obj.decode<String>('content'),
    images: obj.decode<List<String>>('images')!,
    replyToId: obj.decode<String>('replyToId'),
  );

  @override
  Map<String, dynamic> encode(CreateChatMessageRequest value) => {
    'chatId': value.chatId.encode(),
    'content': value.content?.encode(),
    'images': value.images.encode(),
    'replyToId': value.replyToId?.encode(),
  };
}
