// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the CreateReportRequest schema.
final class CreateReportRequest {
  const new({
    required this.type,
    required this.refType,
    required this.refId,
    this.content,
  });

  final ReportType type;
  final ReportRefType refType;
  final String refId;
  final String? content;

  /// OpenAPI codec for encoding and decoding [CreateReportRequest].
  static const codec = _Codec();

  @override
  String toString() => 'CreateReportRequest(type: $type, refType: $refType, refId: $refId, content: $content)';
}

/// OpenAPI codec converting between [CreateReportRequest] and a JSON object.
class _Codec extends OpenApiCodec<CreateReportRequest, Map<String, dynamic>> {
  const new();

  @override
  CreateReportRequest decode(Map<String, dynamic> obj) => .new(
    type: obj.decode<ReportType>('type')!,
    refType: obj.decode<ReportRefType>('refType')!,
    refId: obj.decode<String>('refId')!,
    content: obj.decode<String>('content'),
  );

  @override
  Map<String, dynamic> encode(CreateReportRequest value) => {
    'type': value.type.encode(),
    'refType': value.refType.encode(),
    'refId': value.refId.encode(),
    'content': value.content?.encode(),
  };
}
