// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the CreateCommissionWorkMemo404Response schema.
final class CreateCommissionWorkMemo404Response {
  const new({
    required this.status,
    required this.errorCode,
  });

  final num status;
  final String errorCode;

  /// OpenAPI codec for encoding and decoding [CreateCommissionWorkMemo404Response].
  static const codec = _Codec();

  @override
  String toString() => 'CreateCommissionWorkMemo404Response(status: $status, errorCode: $errorCode)';
}

/// OpenAPI codec converting between [CreateCommissionWorkMemo404Response] and a JSON object.
class _Codec extends OpenApiCodec<CreateCommissionWorkMemo404Response, Map<String, dynamic>> {
  const new();

  @override
  CreateCommissionWorkMemo404Response decode(Map<String, dynamic> obj) => .new(
    status: obj.decode<num>('status')!,
    errorCode: obj.decode<String>('errorCode')!,
  );

  @override
  Map<String, dynamic> encode(CreateCommissionWorkMemo404Response value) => {
    'status': value.status.encode(),
    'errorCode': value.errorCode.encode(),
  };
}
