// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the ErrorResponse schema.
final class ErrorResponse {
  const new({
    required this.statusCode,
    required this.message,
    this.error,
  });

  final num statusCode;
  final dynamic message;
  final String? error;

  /// OpenAPI codec for encoding and decoding [ErrorResponse].
  static const codec = _Codec();

  @override
  String toString() => 'ErrorResponse(statusCode: $statusCode, message: $message, error: $error)';
}

/// OpenAPI codec converting between [ErrorResponse] and a JSON object.
class _Codec extends OpenApiCodec<ErrorResponse, Map<String, dynamic>> {
  const new();

  @override
  ErrorResponse decode(Map<String, dynamic> obj) => .new(
    statusCode: obj.decode<num>('statusCode')!,
    message: obj.decode<dynamic>('message')!,
    error: obj.decode<String>('error'),
  );

  @override
  Map<String, dynamic> encode(ErrorResponse value) => {
    'statusCode': value.statusCode.encode(),
    'message': value.message.encode(),
    'error': value.error?.encode(),
  };
}
