// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the FeedRankingsResponse schema.
final class FeedRankingsResponse {
  const new({
    required this.feeds,
  });

  final List<FeedRankingResponse> feeds;

  /// OpenAPI codec for encoding and decoding [FeedRankingsResponse].
  static const codec = _Codec();

  @override
  String toString() => 'FeedRankingsResponse(feeds: $feeds)';
}

/// OpenAPI codec converting between [FeedRankingsResponse] and a JSON object.
class _Codec extends OpenApiCodec<FeedRankingsResponse, Map<String, dynamic>> {
  const new();

  @override
  FeedRankingsResponse decode(Map<String, dynamic> obj) => .new(
    feeds: obj.decode<List<FeedRankingResponse>>('feeds')!,
  );

  @override
  Map<String, dynamic> encode(FeedRankingsResponse value) => {
    'feeds': value.feeds.encode(),
  };
}
