// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the FeedRankingResponse schema.
final class FeedRankingResponse {
  const new({
    required this.id,
    required this.title,
    required this.thumbnail,
    required this.likeCount,
    required this.viewCount,
    required this.isLike,
    required this.author,
  });

  final String id;
  final String title;
  final String thumbnail;
  final num likeCount;
  final num viewCount;
  final bool isLike;
  final UserBaseResponse author;

  /// OpenAPI codec for encoding and decoding [FeedRankingResponse].
  static const codec = _Codec();

  @override
  String toString() =>
      'FeedRankingResponse(id: $id, title: $title, thumbnail: $thumbnail, likeCount: $likeCount, viewCount: $viewCount, isLike: $isLike, author: $author)';
}

/// OpenAPI codec converting between [FeedRankingResponse] and a JSON object.
class _Codec extends OpenApiCodec<FeedRankingResponse, Map<String, dynamic>> {
  const new();

  @override
  FeedRankingResponse decode(Map<String, dynamic> obj) => .new(
    id: obj.decode<String>('id')!,
    title: obj.decode<String>('title')!,
    thumbnail: obj.decode<String>('thumbnail')!,
    likeCount: obj.decode<num>('likeCount')!,
    viewCount: obj.decode<num>('viewCount')!,
    isLike: obj.decode<bool>('isLike')!,
    author: obj.decode<UserBaseResponse>('author')!,
  );

  @override
  Map<String, dynamic> encode(FeedRankingResponse value) => {
    'id': value.id.encode(),
    'title': value.title.encode(),
    'thumbnail': value.thumbnail.encode(),
    'likeCount': value.likeCount.encode(),
    'viewCount': value.viewCount.encode(),
    'isLike': value.isLike.encode(),
    'author': value.author.encode(),
  };
}
