// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the FeedCommentWithWriterResponse schema.
final class FeedCommentWithWriterResponse {
  const new({
    required this.id,
    required this.content,
    required this.createdAt,
    required this.likeCount,
    required this.writer,
  });

  final String id;
  final String content;
  final DateTime createdAt;
  final num likeCount;
  final UserBaseResponse writer;

  /// OpenAPI codec for encoding and decoding [FeedCommentWithWriterResponse].
  static const codec = _Codec();
}

/// OpenAPI codec converting between [FeedCommentWithWriterResponse] and a JSON object.
class _Codec extends OpenApiCodec<FeedCommentWithWriterResponse, Map<String, dynamic>> {
  const new();

  @override
  FeedCommentWithWriterResponse decode(Map<String, dynamic> obj) => .new(
    id: obj.decode<String>('id')!,
    content: obj.decode<String>('content')!,
    createdAt: obj.decode<DateTime>('createdAt')!,
    likeCount: obj.decode<num>('likeCount')!,
    writer: obj.decode<UserBaseResponse>('writer')!,
  );

  @override
  Map<String, dynamic> encode(FeedCommentWithWriterResponse value) => {
    'id': value.id.encode(),
    'content': value.content.encode(),
    'createdAt': value.createdAt.encode(),
    'likeCount': value.likeCount.encode(),
    'writer': value.writer.encode(),
  };
}
