// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the FeedMetaResponse schema.
final class FeedMetaResponse {
  const new({
    required this.id,
    required this.title,
    required this.thumbnail,
    required this.likeCount,
    required this.viewCount,
    required this.content,
    required this.createdAt,
    required this.tags,
  });

  final String id;
  final String title;
  final String thumbnail;
  final num likeCount;
  final num viewCount;
  final String content;
  final DateTime createdAt;
  final List<String> tags;

  /// OpenAPI codec for encoding and decoding [FeedMetaResponse].
  static const codec = _Codec();

  @override
  String toString() =>
      'FeedMetaResponse(id: $id, title: $title, thumbnail: $thumbnail, likeCount: $likeCount, viewCount: $viewCount, content: $content, createdAt: $createdAt, tags: $tags)';
}

/// OpenAPI codec converting between [FeedMetaResponse] and a JSON object.
class _Codec extends OpenApiCodec<FeedMetaResponse, Map<String, dynamic>> {
  const new();

  @override
  FeedMetaResponse decode(Map<String, dynamic> obj) => .new(
    id: obj.decode<String>('id')!,
    title: obj.decode<String>('title')!,
    thumbnail: obj.decode<String>('thumbnail')!,
    likeCount: obj.decode<num>('likeCount')!,
    viewCount: obj.decode<num>('viewCount')!,
    content: obj.decode<String>('content')!,
    createdAt: obj.decode<DateTime>('createdAt')!,
    tags: obj.decode<List<String>>('tags')!,
  );

  @override
  Map<String, dynamic> encode(FeedMetaResponse value) => {
    'id': value.id.encode(),
    'title': value.title.encode(),
    'thumbnail': value.thumbnail.encode(),
    'likeCount': value.likeCount.encode(),
    'viewCount': value.viewCount.encode(),
    'content': value.content.encode(),
    'createdAt': value.createdAt.encode(),
    'tags': value.tags.encode(),
  };
}
