// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the FollowingFeedsResponse schema.
final class FollowingFeedsResponse {
  const new({
    this.nextCursor,
    required this.feeds,
  });

  final String? nextCursor;
  final List<FollowingFeedResponse> feeds;

  /// OpenAPI codec for encoding and decoding [FollowingFeedsResponse].
  static const codec = _Codec();

  @override
  String toString() => 'FollowingFeedsResponse(nextCursor: $nextCursor, feeds: $feeds)';
}

/// OpenAPI codec converting between [FollowingFeedsResponse] and a JSON object.
class _Codec extends OpenApiCodec<FollowingFeedsResponse, Map<String, dynamic>> {
  const new();

  @override
  FollowingFeedsResponse decode(Map<String, dynamic> obj) => .new(
    nextCursor: obj.decode<String>('nextCursor'),
    feeds: obj.decode<List<FollowingFeedResponse>>('feeds')!,
  );

  @override
  Map<String, dynamic> encode(FollowingFeedsResponse value) => {
    'nextCursor': value.nextCursor?.encode(),
    'feeds': value.feeds.encode(),
  };
}
