// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the FollowerUserResponse schema.
final class FollowerUserResponse {
  const new({
    required this.id,
    required this.name,
    this.image,
    required this.url,
    required this.description,
    required this.isFollowing,
  });

  final String id;
  final String name;
  final String? image;
  final String url;
  final String description;
  final bool isFollowing;

  /// OpenAPI codec for encoding and decoding [FollowerUserResponse].
  static const codec = _Codec();

  @override
  String toString() =>
      'FollowerUserResponse(id: $id, name: $name, image: $image, url: $url, description: $description, isFollowing: $isFollowing)';
}

/// OpenAPI codec converting between [FollowerUserResponse] and a JSON object.
class _Codec extends OpenApiCodec<FollowerUserResponse, Map<String, dynamic>> {
  const new();

  @override
  FollowerUserResponse decode(Map<String, dynamic> obj) => .new(
    id: obj.decode<String>('id')!,
    name: obj.decode<String>('name')!,
    image: obj.decode<String>('image'),
    url: obj.decode<String>('url')!,
    description: obj.decode<String>('description')!,
    isFollowing: obj.decode<bool>('isFollowing')!,
  );

  @override
  Map<String, dynamic> encode(FollowerUserResponse value) => {
    'id': value.id.encode(),
    'name': value.name.encode(),
    'image': value.image?.encode(),
    'url': value.url.encode(),
    'description': value.description.encode(),
    'isFollowing': value.isFollowing.encode(),
  };
}
