// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the FollowingFeedResponse schema.
final class FollowingFeedResponse {
  const new({
    required this.id,
    required this.title,
    required this.thumbnail,
    required this.likeCount,
    required this.viewCount,
    required this.cards,
    required this.createdAt,
    required this.content,
    required this.tags,
    required this.commentCount,
    required this.isLike,
    required this.isSave,
    this.comment,
    required this.author,
  });

  final String id;
  final String title;
  final String thumbnail;
  final num likeCount;
  final num viewCount;
  final List<String> cards;
  final DateTime createdAt;
  final String content;
  final List<String> tags;
  final num commentCount;
  final bool isLike;
  final bool isSave;
  final FeedCommentWithWriterResponse? comment;
  final UserBaseResponse author;

  /// OpenAPI codec for encoding and decoding [FollowingFeedResponse].
  static const codec = _Codec();

  @override
  String toString() =>
      'FollowingFeedResponse(id: $id, title: $title, thumbnail: $thumbnail, likeCount: $likeCount, viewCount: $viewCount, cards: $cards, createdAt: $createdAt, content: $content, tags: $tags, commentCount: $commentCount, isLike: $isLike, isSave: $isSave, comment: $comment, author: $author)';
}

/// OpenAPI codec converting between [FollowingFeedResponse] and a JSON object.
class _Codec extends OpenApiCodec<FollowingFeedResponse, Map<String, dynamic>> {
  const new();

  @override
  FollowingFeedResponse decode(Map<String, dynamic> obj) => .new(
    id: obj.decode<String>('id')!,
    title: obj.decode<String>('title')!,
    thumbnail: obj.decode<String>('thumbnail')!,
    likeCount: obj.decode<num>('likeCount')!,
    viewCount: obj.decode<num>('viewCount')!,
    cards: obj.decode<List<String>>('cards')!,
    createdAt: obj.decode<DateTime>('createdAt')!,
    content: obj.decode<String>('content')!,
    tags: obj.decode<List<String>>('tags')!,
    commentCount: obj.decode<num>('commentCount')!,
    isLike: obj.decode<bool>('isLike')!,
    isSave: obj.decode<bool>('isSave')!,
    comment: obj.decode<FeedCommentWithWriterResponse>('comment'),
    author: obj.decode<UserBaseResponse>('author')!,
  );

  @override
  Map<String, dynamic> encode(FollowingFeedResponse value) => {
    'id': value.id.encode(),
    'title': value.title.encode(),
    'thumbnail': value.thumbnail.encode(),
    'likeCount': value.likeCount.encode(),
    'viewCount': value.viewCount.encode(),
    'cards': value.cards.encode(),
    'createdAt': value.createdAt.encode(),
    'content': value.content.encode(),
    'tags': value.tags.encode(),
    'commentCount': value.commentCount.encode(),
    'isLike': value.isLike.encode(),
    'isSave': value.isSave.encode(),
    'comment': value.comment?.encode(),
    'author': value.author.encode(),
  };
}
