// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the GetImageUploadUrlRequest schema.
final class GetImageUploadUrlRequest {
  const new({
    required this.type,
    required this.ext,
    required this.width,
    required this.height,
    this.fileName,
  });

  final ImageType type;
  final ImageExt ext;
  final num width;
  final num height;
  final String? fileName;

  /// OpenAPI codec for encoding and decoding [GetImageUploadUrlRequest].
  static const codec = _Codec();

  @override
  String toString() =>
      'GetImageUploadUrlRequest(type: $type, ext: $ext, width: $width, height: $height, fileName: $fileName)';
}

/// OpenAPI codec converting between [GetImageUploadUrlRequest] and a JSON object.
class _Codec extends OpenApiCodec<GetImageUploadUrlRequest, Map<String, dynamic>> {
  const new();

  @override
  GetImageUploadUrlRequest decode(Map<String, dynamic> obj) => .new(
    type: obj.decode<ImageType>('type')!,
    ext: obj.decode<ImageExt>('ext')!,
    width: obj.decode<num>('width')!,
    height: obj.decode<num>('height')!,
    fileName: obj.decode<String>('fileName'),
  );

  @override
  Map<String, dynamic> encode(GetImageUploadUrlRequest value) => {
    'type': value.type.encode(),
    'ext': value.ext.encode(),
    'width': value.width.encode(),
    'height': value.height.encode(),
    'fileName': value.fileName?.encode(),
  };
}
