// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the IdResponse schema.
final class IdResponse {
  const new({
    required this.id,
  });

  final String id;

  /// OpenAPI codec for encoding and decoding [IdResponse].
  static const codec = _Codec();
}

/// OpenAPI codec converting between [IdResponse] and a JSON object.
class _Codec extends OpenApiCodec<IdResponse, Map<String, dynamic>> {
  const new();

  @override
  IdResponse decode(Map<String, dynamic> obj) => .new(
    id: obj.decode<String>('id')!,
  );

  @override
  Map<String, dynamic> encode(IdResponse value) => {
    'id': value.id.encode(),
  };
}
