// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the ImageUploadUrlResponse schema.
final class ImageUploadUrlResponse {
  const new({
    required this.uploadUrl,
    required this.imageName,
    required this.imageUrl,
  });

  final String uploadUrl;
  final String imageName;
  final String imageUrl;

  /// OpenAPI codec for encoding and decoding [ImageUploadUrlResponse].
  static const codec = _Codec();
}

/// OpenAPI codec converting between [ImageUploadUrlResponse] and a JSON object.
class _Codec extends OpenApiCodec<ImageUploadUrlResponse, Map<String, dynamic>> {
  const new();

  @override
  ImageUploadUrlResponse decode(Map<String, dynamic> obj) => .new(
    uploadUrl: obj.decode<String>('uploadUrl')!,
    imageName: obj.decode<String>('imageName')!,
    imageUrl: obj.decode<String>('imageUrl')!,
  );

  @override
  Map<String, dynamic> encode(ImageUploadUrlResponse value) => {
    'uploadUrl': value.uploadUrl.encode(),
    'imageName': value.imageName.encode(),
    'imageUrl': value.imageUrl.encode(),
  };
}
