// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the InsertFeedsRequest schema.
final class InsertFeedsRequest {
  const new({
    required this.ids,
  });

  final List<String> ids;

  /// OpenAPI codec for encoding and decoding [InsertFeedsRequest].
  static const codec = _Codec();

  @override
  String toString() => 'InsertFeedsRequest(ids: $ids)';
}

/// OpenAPI codec converting between [InsertFeedsRequest] and a JSON object.
class _Codec extends OpenApiCodec<InsertFeedsRequest, Map<String, dynamic>> {
  const new();

  @override
  InsertFeedsRequest decode(Map<String, dynamic> obj) => .new(
    ids: obj.decode<List<String>>('ids')!,
  );

  @override
  Map<String, dynamic> encode(InsertFeedsRequest value) => {
    'ids': value.ids.encode(),
  };
}
