// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the JoinChatRequest schema.
final class JoinChatRequest {
  const new({
    required this.socketId,
  });

  final String socketId;

  /// OpenAPI codec for encoding and decoding [JoinChatRequest].
  static const codec = _Codec();

  @override
  String toString() => 'JoinChatRequest(socketId: $socketId)';
}

/// OpenAPI codec converting between [JoinChatRequest] and a JSON object.
class _Codec extends OpenApiCodec<JoinChatRequest, Map<String, dynamic>> {
  const new();

  @override
  JoinChatRequest decode(Map<String, dynamic> obj) => .new(
    socketId: obj.decode<String>('socketId')!,
  );

  @override
  Map<String, dynamic> encode(JoinChatRequest value) => {
    'socketId': value.socketId.encode(),
  };
}
