// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the JwtResponse schema.
final class JwtResponse {
  const new({
    required this.accessToken,
    required this.refreshToken,
  });

  final String accessToken;
  final String refreshToken;

  /// OpenAPI codec for encoding and decoding [JwtResponse].
  static const codec = _Codec();
}

/// OpenAPI codec converting between [JwtResponse] and a JSON object.
class _Codec extends OpenApiCodec<JwtResponse, Map<String, dynamic>> {
  const new();

  @override
  JwtResponse decode(Map<String, dynamic> obj) => .new(
    accessToken: obj.decode<String>('accessToken')!,
    refreshToken: obj.decode<String>('refreshToken')!,
  );

  @override
  Map<String, dynamic> encode(JwtResponse value) => {
    'accessToken': value.accessToken.encode(),
    'refreshToken': value.refreshToken.encode(),
  };
}
