// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the LastChatMessageResponse schema.
final class LastChatMessageResponse {
  const new({
    required this.id,
    this.content,
    this.image,
    required this.images,
    required this.createdAt,
    required this.senderId,
  });

  final String id;
  final String? content;
  final String? image;
  final List<String> images;
  final DateTime createdAt;
  final String senderId;

  /// OpenAPI codec for encoding and decoding [LastChatMessageResponse].
  static const codec = _Codec();
}

/// OpenAPI codec converting between [LastChatMessageResponse] and a JSON object.
class _Codec extends OpenApiCodec<LastChatMessageResponse, Map<String, dynamic>> {
  const new();

  @override
  LastChatMessageResponse decode(Map<String, dynamic> obj) => .new(
    id: obj.decode<String>('id')!,
    content: obj.decode<String>('content'),
    image: obj.decode<String>('image'),
    images: obj.decode<List<String>>('images')!,
    createdAt: obj.decode<DateTime>('createdAt')!,
    senderId: obj.decode<String>('senderId')!,
  );

  @override
  Map<String, dynamic> encode(LastChatMessageResponse value) => {
    'id': value.id.encode(),
    'content': value.content?.encode(),
    'image': value.image?.encode(),
    'images': value.images.encode(),
    'createdAt': value.createdAt.encode(),
    'senderId': value.senderId.encode(),
  };
}
