// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the LatestFeedResponse schema.
final class LatestFeedResponse {
  const new({
    required this.id,
    required this.title,
    required this.thumbnail,
    required this.likeCount,
    required this.viewCount,
    required this.author,
    required this.createdAt,
    required this.isLike,
  });

  final String id;
  final String title;
  final String thumbnail;
  final num likeCount;
  final num viewCount;
  final UserBaseResponse author;
  final DateTime createdAt;
  final bool isLike;

  /// OpenAPI codec for encoding and decoding [LatestFeedResponse].
  static const codec = _Codec();

  @override
  String toString() =>
      'LatestFeedResponse(id: $id, title: $title, thumbnail: $thumbnail, likeCount: $likeCount, viewCount: $viewCount, author: $author, createdAt: $createdAt, isLike: $isLike)';
}

/// OpenAPI codec converting between [LatestFeedResponse] and a JSON object.
class _Codec extends OpenApiCodec<LatestFeedResponse, Map<String, dynamic>> {
  const new();

  @override
  LatestFeedResponse decode(Map<String, dynamic> obj) => .new(
    id: obj.decode<String>('id')!,
    title: obj.decode<String>('title')!,
    thumbnail: obj.decode<String>('thumbnail')!,
    likeCount: obj.decode<num>('likeCount')!,
    viewCount: obj.decode<num>('viewCount')!,
    author: obj.decode<UserBaseResponse>('author')!,
    createdAt: obj.decode<DateTime>('createdAt')!,
    isLike: obj.decode<bool>('isLike')!,
  );

  @override
  Map<String, dynamic> encode(LatestFeedResponse value) => {
    'id': value.id.encode(),
    'title': value.title.encode(),
    'thumbnail': value.thumbnail.encode(),
    'likeCount': value.likeCount.encode(),
    'viewCount': value.viewCount.encode(),
    'author': value.author.encode(),
    'createdAt': value.createdAt.encode(),
    'isLike': value.isLike.encode(),
  };
}
