// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the LatestFeedsResponse schema.
final class LatestFeedsResponse {
  const new({
    this.nextCursor,
    required this.feeds,
  });

  final String? nextCursor;
  final List<LatestFeedResponse> feeds;

  /// OpenAPI codec for encoding and decoding [LatestFeedsResponse].
  static const codec = _Codec();

  @override
  String toString() => 'LatestFeedsResponse(nextCursor: $nextCursor, feeds: $feeds)';
}

/// OpenAPI codec converting between [LatestFeedsResponse] and a JSON object.
class _Codec extends OpenApiCodec<LatestFeedsResponse, Map<String, dynamic>> {
  const new();

  @override
  LatestFeedsResponse decode(Map<String, dynamic> obj) => .new(
    nextCursor: obj.decode<String>('nextCursor'),
    feeds: obj.decode<List<LatestFeedResponse>>('feeds')!,
  );

  @override
  Map<String, dynamic> encode(LatestFeedsResponse value) => {
    'nextCursor': value.nextCursor?.encode(),
    'feeds': value.feeds.encode(),
  };
}
