// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the LeaveChatRequest schema.
final class LeaveChatRequest {
  const new({
    required this.socketId,
  });

  final String socketId;

  /// OpenAPI codec for encoding and decoding [LeaveChatRequest].
  static const codec = _Codec();

  @override
  String toString() => 'LeaveChatRequest(socketId: $socketId)';
}

/// OpenAPI codec converting between [LeaveChatRequest] and a JSON object.
class _Codec extends OpenApiCodec<LeaveChatRequest, Map<String, dynamic>> {
  const new();

  @override
  LeaveChatRequest decode(Map<String, dynamic> obj) => .new(
    socketId: obj.decode<String>('socketId')!,
  );

  @override
  Map<String, dynamic> encode(LeaveChatRequest value) => {
    'socketId': value.socketId.encode(),
  };
}
