// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the LoginResponse schema.
final class LoginResponse {
  const new({
    required this.accessToken,
    required this.refreshToken,
    required this.id,
  });

  final String accessToken;
  final String refreshToken;
  final String id;

  /// OpenAPI codec for encoding and decoding [LoginResponse].
  static const codec = _Codec();
}

/// OpenAPI codec converting between [LoginResponse] and a JSON object.
class _Codec extends OpenApiCodec<LoginResponse, Map<String, dynamic>> {
  const new();

  @override
  LoginResponse decode(Map<String, dynamic> obj) => .new(
    accessToken: obj.decode<String>('accessToken')!,
    refreshToken: obj.decode<String>('refreshToken')!,
    id: obj.decode<String>('id')!,
  );

  @override
  Map<String, dynamic> encode(LoginResponse value) => {
    'accessToken': value.accessToken.encode(),
    'refreshToken': value.refreshToken.encode(),
    'id': value.id.encode(),
  };
}
