// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the LoginRequest schema.
final class LoginRequest {
  const new({
    required this.provider,
    required this.providerAccessToken,
    this.deviceId,
  });

  final AuthProvider provider;
  final String providerAccessToken;
  final String? deviceId;

  /// OpenAPI codec for encoding and decoding [LoginRequest].
  static const codec = _Codec();
}

/// OpenAPI codec converting between [LoginRequest] and a JSON object.
class _Codec extends OpenApiCodec<LoginRequest, Map<String, dynamic>> {
  const new();

  @override
  LoginRequest decode(Map<String, dynamic> obj) => .new(
    provider: obj.decode<AuthProvider>('provider')!,
    providerAccessToken: obj.decode<String>('providerAccessToken')!,
    deviceId: obj.decode<String>('deviceId'),
  );

  @override
  Map<String, dynamic> encode(LoginRequest value) => {
    'provider': value.provider.encode(),
    'providerAccessToken': value.providerAccessToken.encode(),
    'deviceId': value.deviceId?.encode(),
  };
}
