// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the MyBlockingsResponse schema.
final class MyBlockingsResponse {
  const new({
    required this.users,
  });

  final List<UserBaseResponse> users;

  /// OpenAPI codec for encoding and decoding [MyBlockingsResponse].
  static const codec = _Codec();
}

/// OpenAPI codec converting between [MyBlockingsResponse] and a JSON object.
class _Codec extends OpenApiCodec<MyBlockingsResponse, Map<String, dynamic>> {
  const new();

  @override
  MyBlockingsResponse decode(Map<String, dynamic> obj) => .new(
    users: obj.decode<List<UserBaseResponse>>('users')!,
  );

  @override
  Map<String, dynamic> encode(MyBlockingsResponse value) => {
    'users': value.users.encode(),
  };
}
