// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the MyFollowingsResponse schema.
final class MyFollowingsResponse {
  const new({
    this.nextCursor,
    required this.followings,
  });

  final String? nextCursor;
  final List<FollowUserResponse> followings;

  /// OpenAPI codec for encoding and decoding [MyFollowingsResponse].
  static const codec = _Codec();

  @override
  String toString() => 'MyFollowingsResponse(nextCursor: $nextCursor, followings: $followings)';
}

/// OpenAPI codec converting between [MyFollowingsResponse] and a JSON object.
class _Codec extends OpenApiCodec<MyFollowingsResponse, Map<String, dynamic>> {
  const new();

  @override
  MyFollowingsResponse decode(Map<String, dynamic> obj) => .new(
    nextCursor: obj.decode<String>('nextCursor'),
    followings: obj.decode<List<FollowUserResponse>>('followings')!,
  );

  @override
  Map<String, dynamic> encode(MyFollowingsResponse value) => {
    'nextCursor': value.nextCursor?.encode(),
    'followings': value.followings.encode(),
  };
}
