// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the MyFollowersResponse schema.
final class MyFollowersResponse {
  const new({
    this.nextCursor,
    required this.followers,
  });

  final String? nextCursor;
  final List<FollowerUserResponse> followers;

  /// OpenAPI codec for encoding and decoding [MyFollowersResponse].
  static const codec = _Codec();

  @override
  String toString() => 'MyFollowersResponse(nextCursor: $nextCursor, followers: $followers)';
}

/// OpenAPI codec converting between [MyFollowersResponse] and a JSON object.
class _Codec extends OpenApiCodec<MyFollowersResponse, Map<String, dynamic>> {
  const new();

  @override
  MyFollowersResponse decode(Map<String, dynamic> obj) => .new(
    nextCursor: obj.decode<String>('nextCursor'),
    followers: obj.decode<List<FollowerUserResponse>>('followers')!,
  );

  @override
  Map<String, dynamic> encode(MyFollowersResponse value) => {
    'nextCursor': value.nextCursor?.encode(),
    'followers': value.followers.encode(),
  };
}
