// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the MyIdentityVerificationResponse schema.
final class MyIdentityVerificationResponse {
  const new({
    required this.isVerified,
    this.name,
    this.birthDate,
  });

  final bool isVerified;
  final String? name;
  final String? birthDate;

  /// OpenAPI codec for encoding and decoding [MyIdentityVerificationResponse].
  static const codec = _Codec();

  @override
  String toString() => 'MyIdentityVerificationResponse(isVerified: $isVerified, name: $name, birthDate: $birthDate)';
}

/// OpenAPI codec converting between [MyIdentityVerificationResponse] and a JSON object.
class _Codec extends OpenApiCodec<MyIdentityVerificationResponse, Map<String, dynamic>> {
  const new();

  @override
  MyIdentityVerificationResponse decode(Map<String, dynamic> obj) => .new(
    isVerified: obj.decode<bool>('isVerified')!,
    name: obj.decode<String>('name'),
    birthDate: obj.decode<String>('birthDate'),
  );

  @override
  Map<String, dynamic> encode(MyIdentityVerificationResponse value) => {
    'isVerified': value.isVerified.encode(),
    'name': value.name?.encode(),
    'birthDate': value.birthDate?.encode(),
  };
}
