// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the MyLikeFeedResponse schema.
final class MyLikeFeedResponse {
  const new({
    required this.id,
    required this.title,
    required this.thumbnail,
    required this.likeCount,
    required this.viewCount,
    required this.cards,
    required this.commentCount,
    required this.createdAt,
    required this.author,
  });

  final String id;
  final String title;
  final String thumbnail;
  final num likeCount;
  final num viewCount;
  final List<String> cards;
  final num commentCount;
  final DateTime createdAt;
  final UserBaseResponse author;

  /// OpenAPI codec for encoding and decoding [MyLikeFeedResponse].
  static const codec = _Codec();

  @override
  String toString() =>
      'MyLikeFeedResponse(id: $id, title: $title, thumbnail: $thumbnail, likeCount: $likeCount, viewCount: $viewCount, cards: $cards, commentCount: $commentCount, createdAt: $createdAt, author: $author)';
}

/// OpenAPI codec converting between [MyLikeFeedResponse] and a JSON object.
class _Codec extends OpenApiCodec<MyLikeFeedResponse, Map<String, dynamic>> {
  const new();

  @override
  MyLikeFeedResponse decode(Map<String, dynamic> obj) => .new(
    id: obj.decode<String>('id')!,
    title: obj.decode<String>('title')!,
    thumbnail: obj.decode<String>('thumbnail')!,
    likeCount: obj.decode<num>('likeCount')!,
    viewCount: obj.decode<num>('viewCount')!,
    cards: obj.decode<List<String>>('cards')!,
    commentCount: obj.decode<num>('commentCount')!,
    createdAt: obj.decode<DateTime>('createdAt')!,
    author: obj.decode<UserBaseResponse>('author')!,
  );

  @override
  Map<String, dynamic> encode(MyLikeFeedResponse value) => {
    'id': value.id.encode(),
    'title': value.title.encode(),
    'thumbnail': value.thumbnail.encode(),
    'likeCount': value.likeCount.encode(),
    'viewCount': value.viewCount.encode(),
    'cards': value.cards.encode(),
    'commentCount': value.commentCount.encode(),
    'createdAt': value.createdAt.encode(),
    'author': value.author.encode(),
  };
}
