// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the MyLikePostsResponse schema.
final class MyLikePostsResponse {
  const new({
    required this.totalCount,
    required this.posts,
  });

  final num totalCount;
  final List<PostWithAuthorResponse> posts;

  /// OpenAPI codec for encoding and decoding [MyLikePostsResponse].
  static const codec = _Codec();

  @override
  String toString() => 'MyLikePostsResponse(totalCount: $totalCount, posts: $posts)';
}

/// OpenAPI codec converting between [MyLikePostsResponse] and a JSON object.
class _Codec extends OpenApiCodec<MyLikePostsResponse, Map<String, dynamic>> {
  const new();

  @override
  MyLikePostsResponse decode(Map<String, dynamic> obj) => .new(
    totalCount: obj.decode<num>('totalCount')!,
    posts: obj.decode<List<PostWithAuthorResponse>>('posts')!,
  );

  @override
  Map<String, dynamic> encode(MyLikePostsResponse value) => {
    'totalCount': value.totalCount.encode(),
    'posts': value.posts.encode(),
  };
}
