// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the MyLikeFeedsResponse schema.
final class MyLikeFeedsResponse {
  const new({
    this.nextCursor,
    required this.feeds,
  });

  final String? nextCursor;
  final List<MyLikeFeedResponse> feeds;

  /// OpenAPI codec for encoding and decoding [MyLikeFeedsResponse].
  static const codec = _Codec();
}

/// OpenAPI codec converting between [MyLikeFeedsResponse] and a JSON object.
class _Codec extends OpenApiCodec<MyLikeFeedsResponse, Map<String, dynamic>> {
  const new();

  @override
  MyLikeFeedsResponse decode(Map<String, dynamic> obj) => .new(
    nextCursor: obj.decode<String>('nextCursor'),
    feeds: obj.decode<List<MyLikeFeedResponse>>('feeds')!,
  );

  @override
  Map<String, dynamic> encode(MyLikeFeedsResponse value) => {
    'nextCursor': value.nextCursor?.encode(),
    'feeds': value.feeds.encode(),
  };
}
