// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the MyProfileResponse schema.
final class MyProfileResponse {
  const new({
    required this.id,
    required this.name,
    this.image,
    required this.url,
    required this.provider,
    required this.email,
    this.backgroundImage,
    required this.description,
    required this.links,
    required this.createdAt,
    required this.hasNotification,
    required this.hasUnreadChatMessage,
    required this.followerCount,
    required this.followingCount,
    required this.isVerified,
  });

  final String id;
  final String name;
  final String? image;
  final String url;
  final SocialProvider provider;
  final String email;
  final String? backgroundImage;
  final String description;
  final List<LinkResponse> links;
  final DateTime createdAt;
  final bool hasNotification;
  final bool hasUnreadChatMessage;
  final num followerCount;
  final num followingCount;
  final bool isVerified;

  /// OpenAPI codec for encoding and decoding [MyProfileResponse].
  static const codec = _Codec();
}

/// OpenAPI codec converting between [MyProfileResponse] and a JSON object.
class _Codec extends OpenApiCodec<MyProfileResponse, Map<String, dynamic>> {
  const new();

  @override
  MyProfileResponse decode(Map<String, dynamic> obj) => .new(
    id: obj.decode<String>('id')!,
    name: obj.decode<String>('name')!,
    image: obj.decode<String>('image'),
    url: obj.decode<String>('url')!,
    provider: obj.decode<SocialProvider>('provider')!,
    email: obj.decode<String>('email')!,
    backgroundImage: obj.decode<String>('backgroundImage'),
    description: obj.decode<String>('description')!,
    links: obj.decode<List<LinkResponse>>('links')!,
    createdAt: obj.decode<DateTime>('createdAt')!,
    hasNotification: obj.decode<bool>('hasNotification')!,
    hasUnreadChatMessage: obj.decode<bool>('hasUnreadChatMessage')!,
    followerCount: obj.decode<num>('followerCount')!,
    followingCount: obj.decode<num>('followingCount')!,
    isVerified: obj.decode<bool>('isVerified')!,
  );

  @override
  Map<String, dynamic> encode(MyProfileResponse value) => {
    'id': value.id.encode(),
    'name': value.name.encode(),
    'image': value.image?.encode(),
    'url': value.url.encode(),
    'provider': value.provider.encode(),
    'email': value.email.encode(),
    'backgroundImage': value.backgroundImage?.encode(),
    'description': value.description.encode(),
    'links': value.links.encode(),
    'createdAt': value.createdAt.encode(),
    'hasNotification': value.hasNotification.encode(),
    'hasUnreadChatMessage': value.hasUnreadChatMessage.encode(),
    'followerCount': value.followerCount.encode(),
    'followingCount': value.followingCount.encode(),
    'isVerified': value.isVerified.encode(),
  };
}
