// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the NotificationResponse schema.
final class NotificationResponse {
  const new({
    required this.id,
    required this.createdAt,
    required this.isRead,
    required this.link,
    this.image,
    required this.message,
  });

  final String id;
  final DateTime createdAt;
  final bool isRead;
  final String link;
  final String? image;
  final String message;

  /// OpenAPI codec for encoding and decoding [NotificationResponse].
  static const codec = _Codec();
}

/// OpenAPI codec converting between [NotificationResponse] and a JSON object.
class _Codec extends OpenApiCodec<NotificationResponse, Map<String, dynamic>> {
  const new();

  @override
  NotificationResponse decode(Map<String, dynamic> obj) => .new(
    id: obj.decode<String>('id')!,
    createdAt: obj.decode<DateTime>('createdAt')!,
    isRead: obj.decode<bool>('isRead')!,
    link: obj.decode<String>('link')!,
    image: obj.decode<String>('image'),
    message: obj.decode<String>('message')!,
  );

  @override
  Map<String, dynamic> encode(NotificationResponse value) => {
    'id': value.id.encode(),
    'createdAt': value.createdAt.encode(),
    'isRead': value.isRead.encode(),
    'link': value.link.encode(),
    'image': value.image?.encode(),
    'message': value.message.encode(),
  };
}
