// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the OpponentUserResponse schema.
final class OpponentUserResponse {
  const new({
    required this.id,
    required this.name,
    this.image,
    required this.url,
    required this.isBlocked,
    required this.isBlocking,
  });

  final String id;
  final String name;
  final String? image;
  final String url;
  final bool isBlocked;
  final bool isBlocking;

  /// OpenAPI codec for encoding and decoding [OpponentUserResponse].
  static const codec = _Codec();

  @override
  String toString() =>
      'OpponentUserResponse(id: $id, name: $name, image: $image, url: $url, isBlocked: $isBlocked, isBlocking: $isBlocking)';
}

/// OpenAPI codec converting between [OpponentUserResponse] and a JSON object.
class _Codec extends OpenApiCodec<OpponentUserResponse, Map<String, dynamic>> {
  const new();

  @override
  OpponentUserResponse decode(Map<String, dynamic> obj) => .new(
    id: obj.decode<String>('id')!,
    name: obj.decode<String>('name')!,
    image: obj.decode<String>('image'),
    url: obj.decode<String>('url')!,
    isBlocked: obj.decode<bool>('isBlocked')!,
    isBlocking: obj.decode<bool>('isBlocking')!,
  );

  @override
  Map<String, dynamic> encode(OpponentUserResponse value) => {
    'id': value.id.encode(),
    'name': value.name.encode(),
    'image': value.image?.encode(),
    'url': value.url.encode(),
    'isBlocked': value.isBlocked.encode(),
    'isBlocking': value.isBlocking.encode(),
  };
}
