// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the ParentPostCommentResponse schema.
final class ParentPostCommentResponse {
  const new({
    required this.id,
    required this.content,
    required this.createdAt,
    required this.likeCount,
    required this.isLike,
    this.writer,
    required this.isDeleted,
    required this.childComments,
  });

  final String id;
  final String content;
  final DateTime createdAt;
  final num likeCount;
  final bool isLike;
  final UserBaseResponse? writer;
  final bool isDeleted;
  final List<ChildPostCommentResponse> childComments;

  /// OpenAPI codec for encoding and decoding [ParentPostCommentResponse].
  static const codec = _Codec();

  @override
  String toString() =>
      'ParentPostCommentResponse(id: $id, content: $content, createdAt: $createdAt, likeCount: $likeCount, isLike: $isLike, writer: $writer, isDeleted: $isDeleted, childComments: $childComments)';
}

/// OpenAPI codec converting between [ParentPostCommentResponse] and a JSON object.
class _Codec extends OpenApiCodec<ParentPostCommentResponse, Map<String, dynamic>> {
  const new();

  @override
  ParentPostCommentResponse decode(Map<String, dynamic> obj) => .new(
    id: obj.decode<String>('id')!,
    content: obj.decode<String>('content')!,
    createdAt: obj.decode<DateTime>('createdAt')!,
    likeCount: obj.decode<num>('likeCount')!,
    isLike: obj.decode<bool>('isLike')!,
    writer: obj.decode<UserBaseResponse>('writer'),
    isDeleted: obj.decode<bool>('isDeleted')!,
    childComments: obj.decode<List<ChildPostCommentResponse>>('childComments')!,
  );

  @override
  Map<String, dynamic> encode(ParentPostCommentResponse value) => {
    'id': value.id.encode(),
    'content': value.content.encode(),
    'createdAt': value.createdAt.encode(),
    'likeCount': value.likeCount.encode(),
    'isLike': value.isLike.encode(),
    'writer': value.writer?.encode(),
    'isDeleted': value.isDeleted.encode(),
    'childComments': value.childComments.encode(),
  };
}
