// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the ParentFeedCommentResponse schema.
final class ParentFeedCommentResponse {
  const new({
    required this.id,
    required this.content,
    required this.createdAt,
    required this.likeCount,
    required this.writer,
    required this.childComments,
    required this.isLike,
  });

  final String id;
  final String content;
  final DateTime createdAt;
  final num likeCount;
  final UserBaseResponse writer;
  final List<ChildFeedCommentResponse> childComments;
  final bool isLike;

  /// OpenAPI codec for encoding and decoding [ParentFeedCommentResponse].
  static const codec = _Codec();
}

/// OpenAPI codec converting between [ParentFeedCommentResponse] and a JSON object.
class _Codec extends OpenApiCodec<ParentFeedCommentResponse, Map<String, dynamic>> {
  const new();

  @override
  ParentFeedCommentResponse decode(Map<String, dynamic> obj) => .new(
    id: obj.decode<String>('id')!,
    content: obj.decode<String>('content')!,
    createdAt: obj.decode<DateTime>('createdAt')!,
    likeCount: obj.decode<num>('likeCount')!,
    writer: obj.decode<UserBaseResponse>('writer')!,
    childComments: obj.decode<List<ChildFeedCommentResponse>>('childComments')!,
    isLike: obj.decode<bool>('isLike')!,
  );

  @override
  Map<String, dynamic> encode(ParentFeedCommentResponse value) => {
    'id': value.id.encode(),
    'content': value.content.encode(),
    'createdAt': value.createdAt.encode(),
    'likeCount': value.likeCount.encode(),
    'writer': value.writer.encode(),
    'childComments': value.childComments.encode(),
    'isLike': value.isLike.encode(),
  };
}
