// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the PopularUserResponse schema.
final class PopularUserResponse {
  const new({
    required this.id,
    required this.name,
    this.image,
    required this.url,
    required this.description,
    required this.followerCount,
    required this.isFollowing,
    required this.thumbnails,
    required this.isBlocking,
    required this.isBlocked,
  });

  final String id;
  final String name;
  final String? image;
  final String url;
  final String description;
  final num followerCount;
  final bool isFollowing;
  final List<String> thumbnails;
  final bool isBlocking;
  final bool isBlocked;

  /// OpenAPI codec for encoding and decoding [PopularUserResponse].
  static const codec = _Codec();
}

/// OpenAPI codec converting between [PopularUserResponse] and a JSON object.
class _Codec extends OpenApiCodec<PopularUserResponse, Map<String, dynamic>> {
  const new();

  @override
  PopularUserResponse decode(Map<String, dynamic> obj) => .new(
    id: obj.decode<String>('id')!,
    name: obj.decode<String>('name')!,
    image: obj.decode<String>('image'),
    url: obj.decode<String>('url')!,
    description: obj.decode<String>('description')!,
    followerCount: obj.decode<num>('followerCount')!,
    isFollowing: obj.decode<bool>('isFollowing')!,
    thumbnails: obj.decode<List<String>>('thumbnails')!,
    isBlocking: obj.decode<bool>('isBlocking')!,
    isBlocked: obj.decode<bool>('isBlocked')!,
  );

  @override
  Map<String, dynamic> encode(PopularUserResponse value) => {
    'id': value.id.encode(),
    'name': value.name.encode(),
    'image': value.image?.encode(),
    'url': value.url.encode(),
    'description': value.description.encode(),
    'followerCount': value.followerCount.encode(),
    'isFollowing': value.isFollowing.encode(),
    'thumbnails': value.thumbnails.encode(),
    'isBlocking': value.isBlocking.encode(),
    'isBlocked': value.isBlocked.encode(),
  };
}
