// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the PopularTagResponse schema.
final class PopularTagResponse {
  const new({
    required this.tagName,
    required this.thumbnail,
  });

  final String tagName;
  final String thumbnail;

  /// OpenAPI codec for encoding and decoding [PopularTagResponse].
  static const codec = _Codec();
}

/// OpenAPI codec converting between [PopularTagResponse] and a JSON object.
class _Codec extends OpenApiCodec<PopularTagResponse, Map<String, dynamic>> {
  const new();

  @override
  PopularTagResponse decode(Map<String, dynamic> obj) => .new(
    tagName: obj.decode<String>('tagName')!,
    thumbnail: obj.decode<String>('thumbnail')!,
  );

  @override
  Map<String, dynamic> encode(PopularTagResponse value) => {
    'tagName': value.tagName.encode(),
    'thumbnail': value.thumbnail.encode(),
  };
}
