// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the PostBaseResponse schema.
final class PostBaseResponse {
  const new({
    required this.id,
    required this.title,
    required this.content,
    this.thumbnail,
    required this.createdAt,
  });

  final String id;
  final String title;
  final String content;
  final String? thumbnail;
  final DateTime createdAt;

  /// OpenAPI codec for encoding and decoding [PostBaseResponse].
  static const codec = _Codec();
}

/// OpenAPI codec converting between [PostBaseResponse] and a JSON object.
class _Codec extends OpenApiCodec<PostBaseResponse, Map<String, dynamic>> {
  const new();

  @override
  PostBaseResponse decode(Map<String, dynamic> obj) => .new(
    id: obj.decode<String>('id')!,
    title: obj.decode<String>('title')!,
    content: obj.decode<String>('content')!,
    thumbnail: obj.decode<String>('thumbnail'),
    createdAt: obj.decode<DateTime>('createdAt')!,
  );

  @override
  Map<String, dynamic> encode(PostBaseResponse value) => {
    'id': value.id.encode(),
    'title': value.title.encode(),
    'content': value.content.encode(),
    'thumbnail': value.thumbnail?.encode(),
    'createdAt': value.createdAt.encode(),
  };
}
