// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the PostsResponse schema.
final class PostsResponse {
  const new({
    required this.totalCount,
    required this.posts,
  });

  final num totalCount;
  final List<PostWithAuthorResponse> posts;

  /// OpenAPI codec for encoding and decoding [PostsResponse].
  static const codec = _Codec();

  @override
  String toString() => 'PostsResponse(totalCount: $totalCount, posts: $posts)';
}

/// OpenAPI codec converting between [PostsResponse] and a JSON object.
class _Codec extends OpenApiCodec<PostsResponse, Map<String, dynamic>> {
  const new();

  @override
  PostsResponse decode(Map<String, dynamic> obj) => .new(
    totalCount: obj.decode<num>('totalCount')!,
    posts: obj.decode<List<PostWithAuthorResponse>>('posts')!,
  );

  @override
  Map<String, dynamic> encode(PostsResponse value) => {
    'totalCount': value.totalCount.encode(),
    'posts': value.posts.encode(),
  };
}
