// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the PostDetailResponse schema.
final class PostDetailResponse {
  const new({
    required this.id,
    required this.title,
    required this.content,
    this.thumbnail,
    required this.createdAt,
    required this.type,
    required this.viewCount,
    required this.commentCount,
    required this.author,
    required this.likeCount,
    required this.isLike,
    required this.isSave,
  });

  final String id;
  final String title;
  final String content;
  final String? thumbnail;
  final DateTime createdAt;
  final PostType type;
  final num viewCount;
  final num commentCount;
  final UserBaseResponse author;
  final num likeCount;
  final bool isLike;
  final bool isSave;

  /// OpenAPI codec for encoding and decoding [PostDetailResponse].
  static const codec = _Codec();

  @override
  String toString() =>
      'PostDetailResponse(id: $id, title: $title, content: $content, thumbnail: $thumbnail, createdAt: $createdAt, type: $type, viewCount: $viewCount, commentCount: $commentCount, author: $author, likeCount: $likeCount, isLike: $isLike, isSave: $isSave)';
}

/// OpenAPI codec converting between [PostDetailResponse] and a JSON object.
class _Codec extends OpenApiCodec<PostDetailResponse, Map<String, dynamic>> {
  const new();

  @override
  PostDetailResponse decode(Map<String, dynamic> obj) => .new(
    id: obj.decode<String>('id')!,
    title: obj.decode<String>('title')!,
    content: obj.decode<String>('content')!,
    thumbnail: obj.decode<String>('thumbnail'),
    createdAt: obj.decode<DateTime>('createdAt')!,
    type: obj.decode<PostType>('type')!,
    viewCount: obj.decode<num>('viewCount')!,
    commentCount: obj.decode<num>('commentCount')!,
    author: obj.decode<UserBaseResponse>('author')!,
    likeCount: obj.decode<num>('likeCount')!,
    isLike: obj.decode<bool>('isLike')!,
    isSave: obj.decode<bool>('isSave')!,
  );

  @override
  Map<String, dynamic> encode(PostDetailResponse value) => {
    'id': value.id.encode(),
    'title': value.title.encode(),
    'content': value.content.encode(),
    'thumbnail': value.thumbnail?.encode(),
    'createdAt': value.createdAt.encode(),
    'type': value.type.encode(),
    'viewCount': value.viewCount.encode(),
    'commentCount': value.commentCount.encode(),
    'author': value.author.encode(),
    'likeCount': value.likeCount.encode(),
    'isLike': value.isLike.encode(),
    'isSave': value.isSave.encode(),
  };
}
