// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the PostWithAuthorResponse schema.
final class PostWithAuthorResponse {
  const new({
    required this.id,
    required this.title,
    required this.content,
    this.thumbnail,
    required this.createdAt,
    required this.type,
    required this.viewCount,
    required this.commentCount,
    required this.author,
  });

  final String id;
  final String title;
  final String content;
  final String? thumbnail;
  final DateTime createdAt;
  final PostType type;
  final num viewCount;
  final num commentCount;
  final UserBaseResponse author;

  /// OpenAPI codec for encoding and decoding [PostWithAuthorResponse].
  static const codec = _Codec();
}

/// OpenAPI codec converting between [PostWithAuthorResponse] and a JSON object.
class _Codec extends OpenApiCodec<PostWithAuthorResponse, Map<String, dynamic>> {
  const new();

  @override
  PostWithAuthorResponse decode(Map<String, dynamic> obj) => .new(
    id: obj.decode<String>('id')!,
    title: obj.decode<String>('title')!,
    content: obj.decode<String>('content')!,
    thumbnail: obj.decode<String>('thumbnail'),
    createdAt: obj.decode<DateTime>('createdAt')!,
    type: obj.decode<PostType>('type')!,
    viewCount: obj.decode<num>('viewCount')!,
    commentCount: obj.decode<num>('commentCount')!,
    author: obj.decode<UserBaseResponse>('author')!,
  );

  @override
  Map<String, dynamic> encode(PostWithAuthorResponse value) => {
    'id': value.id.encode(),
    'title': value.title.encode(),
    'content': value.content.encode(),
    'thumbnail': value.thumbnail?.encode(),
    'createdAt': value.createdAt.encode(),
    'type': value.type.encode(),
    'viewCount': value.viewCount.encode(),
    'commentCount': value.commentCount.encode(),
    'author': value.author.encode(),
  };
}
