// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the Register409Response schema.
final class Register409Response {
  const new({
    required this.statusCode,
    required this.message,
  });

  final num statusCode;
  final String message;

  /// OpenAPI codec for encoding and decoding [Register409Response].
  static const codec = _Codec();
}

/// OpenAPI codec converting between [Register409Response] and a JSON object.
class _Codec extends OpenApiCodec<Register409Response, Map<String, dynamic>> {
  const new();

  @override
  Register409Response decode(Map<String, dynamic> obj) => .new(
    statusCode: obj.decode<num>('statusCode')!,
    message: obj.decode<String>('message')!,
  );

  @override
  Map<String, dynamic> encode(Register409Response value) => {
    'statusCode': value.statusCode.encode(),
    'message': value.message.encode(),
  };
}
