// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the RegisterRequest schema.
final class RegisterRequest {
  const new({
    required this.provider,
    required this.providerAccessToken,
    this.deviceId,
    required this.name,
    this.url,
  });

  final AuthProvider provider;
  final String providerAccessToken;
  final String? deviceId;
  final String name;
  final String? url;

  /// OpenAPI codec for encoding and decoding [RegisterRequest].
  static const codec = _Codec();
}

/// OpenAPI codec converting between [RegisterRequest] and a JSON object.
class _Codec extends OpenApiCodec<RegisterRequest, Map<String, dynamic>> {
  const new();

  @override
  RegisterRequest decode(Map<String, dynamic> obj) => .new(
    provider: obj.decode<AuthProvider>('provider')!,
    providerAccessToken: obj.decode<String>('providerAccessToken')!,
    deviceId: obj.decode<String>('deviceId'),
    name: obj.decode<String>('name')!,
    url: obj.decode<String>('url'),
  );

  @override
  Map<String, dynamic> encode(RegisterRequest value) => {
    'provider': value.provider.encode(),
    'providerAccessToken': value.providerAccessToken.encode(),
    'deviceId': value.deviceId?.encode(),
    'name': value.name.encode(),
    'url': value.url?.encode(),
  };
}
