// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the RegisterPushTokenRequest schema.
final class RegisterPushTokenRequest {
  const new({
    required this.deviceId,
    required this.token,
  });

  final String deviceId;
  final String token;

  /// OpenAPI codec for encoding and decoding [RegisterPushTokenRequest].
  static const codec = _Codec();

  @override
  String toString() => 'RegisterPushTokenRequest(deviceId: $deviceId, token: $token)';
}

/// OpenAPI codec converting between [RegisterPushTokenRequest] and a JSON object.
class _Codec extends OpenApiCodec<RegisterPushTokenRequest, Map<String, dynamic>> {
  const new();

  @override
  RegisterPushTokenRequest decode(Map<String, dynamic> obj) => .new(
    deviceId: obj.decode<String>('deviceId')!,
    token: obj.decode<String>('token')!,
  );

  @override
  Map<String, dynamic> encode(RegisterPushTokenRequest value) => {
    'deviceId': value.deviceId.encode(),
    'token': value.token.encode(),
  };
}
