// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the RejectCommissionWorkRequest schema.
final class RejectCommissionWorkRequest {
  const new({
    this.reason,
  });

  final Map<String, dynamic>? reason;

  /// OpenAPI codec for encoding and decoding [RejectCommissionWorkRequest].
  static const codec = _Codec();
}

/// OpenAPI codec converting between [RejectCommissionWorkRequest] and a JSON object.
class _Codec extends OpenApiCodec<RejectCommissionWorkRequest, Map<String, dynamic>> {
  const new();

  @override
  RejectCommissionWorkRequest decode(Map<String, dynamic> obj) => .new(
    reason: obj.decode<Map<String, dynamic>>('reason'),
  );

  @override
  Map<String, dynamic> encode(RejectCommissionWorkRequest value) => {
    'reason': value.reason?.encode(),
  };
}
