// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the RemoveFeedsAlbumRequest schema.
final class RemoveFeedsAlbumRequest {
  const new({
    required this.ids,
  });

  final List<String> ids;

  /// OpenAPI codec for encoding and decoding [RemoveFeedsAlbumRequest].
  static const codec = _Codec();
}

/// OpenAPI codec converting between [RemoveFeedsAlbumRequest] and a JSON object.
class _Codec extends OpenApiCodec<RemoveFeedsAlbumRequest, Map<String, dynamic>> {
  const new();

  @override
  RemoveFeedsAlbumRequest decode(Map<String, dynamic> obj) => .new(
    ids: obj.decode<List<String>>('ids')!,
  );

  @override
  Map<String, dynamic> encode(RemoveFeedsAlbumRequest value) => {
    'ids': value.ids.encode(),
  };
}
