// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the ReplyToResponse schema.
final class ReplyToResponse {
  const new({
    required this.id,
    this.content,
    this.image,
    required this.images,
    required this.createdAt,
  });

  final String id;
  final String? content;
  final String? image;
  final List<String> images;
  final DateTime createdAt;

  /// OpenAPI codec for encoding and decoding [ReplyToResponse].
  static const codec = _Codec();

  @override
  String toString() =>
      'ReplyToResponse(id: $id, content: $content, image: $image, images: $images, createdAt: $createdAt)';
}

/// OpenAPI codec converting between [ReplyToResponse] and a JSON object.
class _Codec extends OpenApiCodec<ReplyToResponse, Map<String, dynamic>> {
  const new();

  @override
  ReplyToResponse decode(Map<String, dynamic> obj) => .new(
    id: obj.decode<String>('id')!,
    content: obj.decode<String>('content'),
    image: obj.decode<String>('image'),
    images: obj.decode<List<String>>('images')!,
    createdAt: obj.decode<DateTime>('createdAt')!,
  );

  @override
  Map<String, dynamic> encode(ReplyToResponse value) => {
    'id': value.id.encode(),
    'content': value.content?.encode(),
    'image': value.image?.encode(),
    'images': value.images.encode(),
    'createdAt': value.createdAt.encode(),
  };
}
