// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the SearchedUsersResponse schema.
final class SearchedUsersResponse {
  const new({
    this.nextCursor,
    required this.users,
  });

  final String? nextCursor;
  final List<SearchedUserResponse> users;

  /// OpenAPI codec for encoding and decoding [SearchedUsersResponse].
  static const codec = _Codec();

  @override
  String toString() => 'SearchedUsersResponse(nextCursor: $nextCursor, users: $users)';
}

/// OpenAPI codec converting between [SearchedUsersResponse] and a JSON object.
class _Codec extends OpenApiCodec<SearchedUsersResponse, Map<String, dynamic>> {
  const new();

  @override
  SearchedUsersResponse decode(Map<String, dynamic> obj) => .new(
    nextCursor: obj.decode<String>('nextCursor'),
    users: obj.decode<List<SearchedUserResponse>>('users')!,
  );

  @override
  Map<String, dynamic> encode(SearchedUsersResponse value) => {
    'nextCursor': value.nextCursor?.encode(),
    'users': value.users.encode(),
  };
}
