// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the SearchedFeedsResponse schema.
final class SearchedFeedsResponse {
  const new({
    this.nextCursor,
    required this.feeds,
  });

  final String? nextCursor;
  final List<SearchedFeedResponse> feeds;

  /// OpenAPI codec for encoding and decoding [SearchedFeedsResponse].
  static const codec = _Codec();
}

/// OpenAPI codec converting between [SearchedFeedsResponse] and a JSON object.
class _Codec extends OpenApiCodec<SearchedFeedsResponse, Map<String, dynamic>> {
  const new();

  @override
  SearchedFeedsResponse decode(Map<String, dynamic> obj) => .new(
    nextCursor: obj.decode<String>('nextCursor'),
    feeds: obj.decode<List<SearchedFeedResponse>>('feeds')!,
  );

  @override
  Map<String, dynamic> encode(SearchedFeedsResponse value) => {
    'nextCursor': value.nextCursor?.encode(),
    'feeds': value.feeds.encode(),
  };
}
