// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the SearchedUserResponse schema.
final class SearchedUserResponse {
  const new({
    required this.id,
    required this.name,
    this.image,
    required this.url,
    required this.description,
    this.backgroundImage,
    required this.isFollowing,
    required this.followerCount,
    required this.isBlocking,
    required this.isBlocked,
  });

  final String id;
  final String name;
  final String? image;
  final String url;
  final String description;
  final String? backgroundImage;
  final bool isFollowing;
  final num followerCount;
  final bool isBlocking;
  final bool isBlocked;

  /// OpenAPI codec for encoding and decoding [SearchedUserResponse].
  static const codec = _Codec();

  @override
  String toString() =>
      'SearchedUserResponse(id: $id, name: $name, image: $image, url: $url, description: $description, backgroundImage: $backgroundImage, isFollowing: $isFollowing, followerCount: $followerCount, isBlocking: $isBlocking, isBlocked: $isBlocked)';
}

/// OpenAPI codec converting between [SearchedUserResponse] and a JSON object.
class _Codec extends OpenApiCodec<SearchedUserResponse, Map<String, dynamic>> {
  const new();

  @override
  SearchedUserResponse decode(Map<String, dynamic> obj) => .new(
    id: obj.decode<String>('id')!,
    name: obj.decode<String>('name')!,
    image: obj.decode<String>('image'),
    url: obj.decode<String>('url')!,
    description: obj.decode<String>('description')!,
    backgroundImage: obj.decode<String>('backgroundImage'),
    isFollowing: obj.decode<bool>('isFollowing')!,
    followerCount: obj.decode<num>('followerCount')!,
    isBlocking: obj.decode<bool>('isBlocking')!,
    isBlocked: obj.decode<bool>('isBlocked')!,
  );

  @override
  Map<String, dynamic> encode(SearchedUserResponse value) => {
    'id': value.id.encode(),
    'name': value.name.encode(),
    'image': value.image?.encode(),
    'url': value.url.encode(),
    'description': value.description.encode(),
    'backgroundImage': value.backgroundImage?.encode(),
    'isFollowing': value.isFollowing.encode(),
    'followerCount': value.followerCount.encode(),
    'isBlocking': value.isBlocking.encode(),
    'isBlocked': value.isBlocked.encode(),
  };
}
