// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the SubscriptionResponse schema.
final class SubscriptionResponse {
  const new({
    required this.subscription,
  });

  final List<String> subscription;

  /// OpenAPI codec for encoding and decoding [SubscriptionResponse].
  static const codec = _Codec();
}

/// OpenAPI codec converting between [SubscriptionResponse] and a JSON object.
class _Codec extends OpenApiCodec<SubscriptionResponse, Map<String, dynamic>> {
  const new();

  @override
  SubscriptionResponse decode(Map<String, dynamic> obj) => .new(
    subscription: obj.decode<List<String>>('subscription')!,
  );

  @override
  Map<String, dynamic> encode(SubscriptionResponse value) => {
    'subscription': value.subscription.encode(),
  };
}
