// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the UpdateLinkRequest schema.
final class UpdateLinkRequest {
  const new({
    required this.linkName,
    required this.link,
  });

  final String linkName;
  final String link;

  /// OpenAPI codec for encoding and decoding [UpdateLinkRequest].
  static const codec = _Codec();
}

/// OpenAPI codec converting between [UpdateLinkRequest] and a JSON object.
class _Codec extends OpenApiCodec<UpdateLinkRequest, Map<String, dynamic>> {
  const new();

  @override
  UpdateLinkRequest decode(Map<String, dynamic> obj) => .new(
    linkName: obj.decode<String>('linkName')!,
    link: obj.decode<String>('link')!,
  );

  @override
  Map<String, dynamic> encode(UpdateLinkRequest value) => {
    'linkName': value.linkName.encode(),
    'link': value.link.encode(),
  };
}
