// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the UpdateBackgroundImageRequest schema.
final class UpdateBackgroundImageRequest {
  const new({
    required this.imageName,
  });

  final String imageName;

  /// OpenAPI codec for encoding and decoding [UpdateBackgroundImageRequest].
  static const codec = _Codec();
}

/// OpenAPI codec converting between [UpdateBackgroundImageRequest] and a JSON object.
class _Codec extends OpenApiCodec<UpdateBackgroundImageRequest, Map<String, dynamic>> {
  const new();

  @override
  UpdateBackgroundImageRequest decode(Map<String, dynamic> obj) => .new(
    imageName: obj.decode<String>('imageName')!,
  );

  @override
  Map<String, dynamic> encode(UpdateBackgroundImageRequest value) => {
    'imageName': value.imageName.encode(),
  };
}
