// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the UpdateFeedRequest schema.
final class UpdateFeedRequest {
  const new({
    required this.title,
    required this.cards,
    required this.content,
    required this.tags,
    required this.thumbnail,
    this.albumId,
  });

  final String title;
  final List<String> cards;
  final String content;
  final List<String> tags;
  final String thumbnail;
  final String? albumId;

  /// OpenAPI codec for encoding and decoding [UpdateFeedRequest].
  static const codec = _Codec();
}

/// OpenAPI codec converting between [UpdateFeedRequest] and a JSON object.
class _Codec extends OpenApiCodec<UpdateFeedRequest, Map<String, dynamic>> {
  const new();

  @override
  UpdateFeedRequest decode(Map<String, dynamic> obj) => .new(
    title: obj.decode<String>('title')!,
    cards: obj.decode<List<String>>('cards')!,
    content: obj.decode<String>('content')!,
    tags: obj.decode<List<String>>('tags')!,
    thumbnail: obj.decode<String>('thumbnail')!,
    albumId: obj.decode<String>('albumId'),
  );

  @override
  Map<String, dynamic> encode(UpdateFeedRequest value) => {
    'title': value.title.encode(),
    'cards': value.cards.encode(),
    'content': value.content.encode(),
    'tags': value.tags.encode(),
    'thumbnail': value.thumbnail.encode(),
    'albumId': value.albumId?.encode(),
  };
}
