// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the UpdateUserRequest schema.
final class UpdateUserRequest {
  const new({
    required this.name,
    required this.url,
    required this.description,
    this.links,
  });

  final String name;
  final String url;
  final String description;
  final List<UpdateLinkRequest>? links;

  /// OpenAPI codec for encoding and decoding [UpdateUserRequest].
  static const codec = _Codec();
}

/// OpenAPI codec converting between [UpdateUserRequest] and a JSON object.
class _Codec extends OpenApiCodec<UpdateUserRequest, Map<String, dynamic>> {
  const new();

  @override
  UpdateUserRequest decode(Map<String, dynamic> obj) => .new(
    name: obj.decode<String>('name')!,
    url: obj.decode<String>('url')!,
    description: obj.decode<String>('description')!,
    links: obj.decode<List<UpdateLinkRequest>>('links'),
  );

  @override
  Map<String, dynamic> encode(UpdateUserRequest value) => {
    'name': value.name.encode(),
    'url': value.url.encode(),
    'description': value.description.encode(),
    'links': value.links?.encode(),
  };
}
