// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the UpdateSubscriptionRequest schema.
final class UpdateSubscriptionRequest {
  const new({
    required this.subscription,
  });

  final List<SubscriptionType> subscription;

  /// OpenAPI codec for encoding and decoding [UpdateSubscriptionRequest].
  static const codec = _Codec();
}

/// OpenAPI codec converting between [UpdateSubscriptionRequest] and a JSON object.
class _Codec extends OpenApiCodec<UpdateSubscriptionRequest, Map<String, dynamic>> {
  const new();

  @override
  UpdateSubscriptionRequest decode(Map<String, dynamic> obj) => .new(
    subscription: obj.decode<List<SubscriptionType>>('subscription')!,
  );

  @override
  Map<String, dynamic> encode(UpdateSubscriptionRequest value) => {
    'subscription': value.subscription.encode(),
  };
}
