// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the UpdateProfileConflictResponse schema.
final class UpdateProfileConflictResponse {
  const new({
    required this.statusCode,
    required this.message,
  });

  final num statusCode;
  final String message;

  /// OpenAPI codec for encoding and decoding [UpdateProfileConflictResponse].
  static const codec = _Codec();

  @override
  String toString() => 'UpdateProfileConflictResponse(statusCode: $statusCode, message: $message)';
}

/// OpenAPI codec converting between [UpdateProfileConflictResponse] and a JSON object.
class _Codec extends OpenApiCodec<UpdateProfileConflictResponse, Map<String, dynamic>> {
  const new();

  @override
  UpdateProfileConflictResponse decode(Map<String, dynamic> obj) => .new(
    statusCode: obj.decode<num>('statusCode')!,
    message: obj.decode<String>('message')!,
  );

  @override
  Map<String, dynamic> encode(UpdateProfileConflictResponse value) => {
    'statusCode': value.statusCode.encode(),
    'message': value.message.encode(),
  };
}
