// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the UpdateProfileImageRequest schema.
final class UpdateProfileImageRequest {
  const new({
    required this.imageName,
  });

  final String imageName;

  /// OpenAPI codec for encoding and decoding [UpdateProfileImageRequest].
  static const codec = _Codec();

  @override
  String toString() => 'UpdateProfileImageRequest(imageName: $imageName)';
}

/// OpenAPI codec converting between [UpdateProfileImageRequest] and a JSON object.
class _Codec extends OpenApiCodec<UpdateProfileImageRequest, Map<String, dynamic>> {
  const new();

  @override
  UpdateProfileImageRequest decode(Map<String, dynamic> obj) => .new(
    imageName: obj.decode<String>('imageName')!,
  );

  @override
  Map<String, dynamic> encode(UpdateProfileImageRequest value) => {
    'imageName': value.imageName.encode(),
  };
}
