// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the UploadCommissionWorkResult403Response schema.
final class UploadCommissionWorkResult403Response {
  const new({
    required this.status,
    required this.errorCode,
  });

  final num status;
  final String errorCode;

  /// OpenAPI codec for encoding and decoding [UploadCommissionWorkResult403Response].
  static const codec = _Codec();
}

/// OpenAPI codec converting between [UploadCommissionWorkResult403Response] and a JSON object.
class _Codec extends OpenApiCodec<UploadCommissionWorkResult403Response, Map<String, dynamic>> {
  const new();

  @override
  UploadCommissionWorkResult403Response decode(Map<String, dynamic> obj) => .new(
    status: obj.decode<num>('status')!,
    errorCode: obj.decode<String>('errorCode')!,
  );

  @override
  Map<String, dynamic> encode(UploadCommissionWorkResult403Response value) => {
    'status': value.status.encode(),
    'errorCode': value.errorCode.encode(),
  };
}
