// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the UploadCommissionWorkResult404Response schema.
final class UploadCommissionWorkResult404Response {
  const new({
    required this.status,
    required this.errorCode,
  });

  final num status;
  final String errorCode;

  /// OpenAPI codec for encoding and decoding [UploadCommissionWorkResult404Response].
  static const codec = _Codec();

  @override
  String toString() => 'UploadCommissionWorkResult404Response(status: $status, errorCode: $errorCode)';
}

/// OpenAPI codec converting between [UploadCommissionWorkResult404Response] and a JSON object.
class _Codec extends OpenApiCodec<UploadCommissionWorkResult404Response, Map<String, dynamic>> {
  const new();

  @override
  UploadCommissionWorkResult404Response decode(Map<String, dynamic> obj) => .new(
    status: obj.decode<num>('status')!,
    errorCode: obj.decode<String>('errorCode')!,
  );

  @override
  Map<String, dynamic> encode(UploadCommissionWorkResult404Response value) => {
    'status': value.status.encode(),
    'errorCode': value.errorCode.encode(),
  };
}
