// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the UpsertCommissionNoticeRequest schema.
final class UpsertCommissionNoticeRequest {
  const new({
    required this.title,
    required this.content,
  });

  final String title;
  final String content;

  /// OpenAPI codec for encoding and decoding [UpsertCommissionNoticeRequest].
  static const codec = _Codec();

  @override
  String toString() => 'UpsertCommissionNoticeRequest(title: $title, content: $content)';
}

/// OpenAPI codec converting between [UpsertCommissionNoticeRequest] and a JSON object.
class _Codec extends OpenApiCodec<UpsertCommissionNoticeRequest, Map<String, dynamic>> {
  const new();

  @override
  UpsertCommissionNoticeRequest decode(Map<String, dynamic> obj) => .new(
    title: obj.decode<String>('title')!,
    content: obj.decode<String>('content')!,
  );

  @override
  Map<String, dynamic> encode(UpsertCommissionNoticeRequest value) => {
    'title': value.title.encode(),
    'content': value.content.encode(),
  };
}
