// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the UserFeedResponse schema.
final class UserFeedResponse {
  const new({
    required this.id,
    required this.title,
    required this.thumbnail,
    required this.likeCount,
    required this.viewCount,
    required this.cards,
    required this.createdAt,
    required this.commentCount,
    required this.isLike,
  });

  final String id;
  final String title;
  final String thumbnail;
  final num likeCount;
  final num viewCount;
  final List<String> cards;
  final DateTime createdAt;
  final num commentCount;
  final bool isLike;

  /// OpenAPI codec for encoding and decoding [UserFeedResponse].
  static const codec = _Codec();
}

/// OpenAPI codec converting between [UserFeedResponse] and a JSON object.
class _Codec extends OpenApiCodec<UserFeedResponse, Map<String, dynamic>> {
  const new();

  @override
  UserFeedResponse decode(Map<String, dynamic> obj) => .new(
    id: obj.decode<String>('id')!,
    title: obj.decode<String>('title')!,
    thumbnail: obj.decode<String>('thumbnail')!,
    likeCount: obj.decode<num>('likeCount')!,
    viewCount: obj.decode<num>('viewCount')!,
    cards: obj.decode<List<String>>('cards')!,
    createdAt: obj.decode<DateTime>('createdAt')!,
    commentCount: obj.decode<num>('commentCount')!,
    isLike: obj.decode<bool>('isLike')!,
  );

  @override
  Map<String, dynamic> encode(UserFeedResponse value) => {
    'id': value.id.encode(),
    'title': value.title.encode(),
    'thumbnail': value.thumbnail.encode(),
    'likeCount': value.likeCount.encode(),
    'viewCount': value.viewCount.encode(),
    'cards': value.cards.encode(),
    'createdAt': value.createdAt.encode(),
    'commentCount': value.commentCount.encode(),
    'isLike': value.isLike.encode(),
  };
}
