// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the UserBaseWithBlockedResponse schema.
final class UserBaseWithBlockedResponse {
  const new({
    required this.id,
    required this.name,
    this.image,
    required this.url,
    required this.isBlocked,
  });

  final String id;
  final String name;
  final String? image;
  final String url;
  final bool isBlocked;

  /// OpenAPI codec for encoding and decoding [UserBaseWithBlockedResponse].
  static const codec = _Codec();

  @override
  String toString() =>
      'UserBaseWithBlockedResponse(id: $id, name: $name, image: $image, url: $url, isBlocked: $isBlocked)';
}

/// OpenAPI codec converting between [UserBaseWithBlockedResponse] and a JSON object.
class _Codec extends OpenApiCodec<UserBaseWithBlockedResponse, Map<String, dynamic>> {
  const new();

  @override
  UserBaseWithBlockedResponse decode(Map<String, dynamic> obj) => .new(
    id: obj.decode<String>('id')!,
    name: obj.decode<String>('name')!,
    image: obj.decode<String>('image'),
    url: obj.decode<String>('url')!,
    isBlocked: obj.decode<bool>('isBlocked')!,
  );

  @override
  Map<String, dynamic> encode(UserBaseWithBlockedResponse value) => {
    'id': value.id.encode(),
    'name': value.name.encode(),
    'image': value.image?.encode(),
    'url': value.url.encode(),
    'isBlocked': value.isBlocked.encode(),
  };
}
