// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the UserFeedsResponse schema.
final class UserFeedsResponse {
  const new({
    this.nextCursor,
    required this.feeds,
  });

  final String? nextCursor;
  final List<UserFeedResponse> feeds;

  /// OpenAPI codec for encoding and decoding [UserFeedsResponse].
  static const codec = _Codec();

  @override
  String toString() => 'UserFeedsResponse(nextCursor: $nextCursor, feeds: $feeds)';
}

/// OpenAPI codec converting between [UserFeedsResponse] and a JSON object.
class _Codec extends OpenApiCodec<UserFeedsResponse, Map<String, dynamic>> {
  const new();

  @override
  UserFeedsResponse decode(Map<String, dynamic> obj) => .new(
    nextCursor: obj.decode<String>('nextCursor'),
    feeds: obj.decode<List<UserFeedResponse>>('feeds')!,
  );

  @override
  Map<String, dynamic> encode(UserFeedsResponse value) => {
    'nextCursor': value.nextCursor?.encode(),
    'feeds': value.feeds.encode(),
  };
}
