// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the UserBaseResponse schema.
final class UserBaseResponse {
  const new({
    required this.id,
    required this.name,
    this.image,
    required this.url,
  });

  final String id;
  final String name;
  final String? image;
  final String url;

  /// OpenAPI codec for encoding and decoding [UserBaseResponse].
  static const codec = _Codec();

  @override
  String toString() => 'UserBaseResponse(id: $id, name: $name, image: $image, url: $url)';
}

/// OpenAPI codec converting between [UserBaseResponse] and a JSON object.
class _Codec extends OpenApiCodec<UserBaseResponse, Map<String, dynamic>> {
  const new();

  @override
  UserBaseResponse decode(Map<String, dynamic> obj) => .new(
    id: obj.decode<String>('id')!,
    name: obj.decode<String>('name')!,
    image: obj.decode<String>('image'),
    url: obj.decode<String>('url')!,
  );

  @override
  Map<String, dynamic> encode(UserBaseResponse value) => {
    'id': value.id.encode(),
    'name': value.name.encode(),
    'image': value.image?.encode(),
    'url': value.url.encode(),
  };
}
