// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the UserMetaResponse schema.
final class UserMetaResponse {
  const new({
    required this.id,
    required this.name,
    this.image,
    required this.url,
    required this.description,
  });

  final String id;
  final String name;
  final String? image;
  final String url;
  final String description;

  /// OpenAPI codec for encoding and decoding [UserMetaResponse].
  static const codec = _Codec();

  @override
  String toString() => 'UserMetaResponse(id: $id, name: $name, image: $image, url: $url, description: $description)';
}

/// OpenAPI codec converting between [UserMetaResponse] and a JSON object.
class _Codec extends OpenApiCodec<UserMetaResponse, Map<String, dynamic>> {
  const new();

  @override
  UserMetaResponse decode(Map<String, dynamic> obj) => .new(
    id: obj.decode<String>('id')!,
    name: obj.decode<String>('name')!,
    image: obj.decode<String>('image'),
    url: obj.decode<String>('url')!,
    description: obj.decode<String>('description')!,
  );

  @override
  Map<String, dynamic> encode(UserMetaResponse value) => {
    'id': value.id.encode(),
    'name': value.name.encode(),
    'image': value.image?.encode(),
    'url': value.url.encode(),
    'description': value.description.encode(),
  };
}
