// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the UserProfileResponse schema.
final class UserProfileResponse {
  const new({
    required this.id,
    required this.name,
    this.image,
    required this.url,
    required this.isBlocked,
    required this.description,
    this.backgroundImage,
    required this.links,
    required this.followerCount,
    required this.followingCount,
    required this.feedCount,
    required this.postCount,
    required this.isFollowing,
    required this.isBlocking,
    required this.albums,
  });

  final String id;
  final String name;
  final String? image;
  final String url;
  final bool isBlocked;
  final String description;
  final String? backgroundImage;
  final List<LinkResponse> links;
  final num followerCount;
  final num followingCount;
  final num feedCount;
  final num postCount;
  final bool isFollowing;
  final bool isBlocking;
  final List<AlbumWithCountResponse> albums;

  /// OpenAPI codec for encoding and decoding [UserProfileResponse].
  static const codec = _Codec();

  @override
  String toString() =>
      'UserProfileResponse(id: $id, name: $name, image: $image, url: $url, isBlocked: $isBlocked, description: $description, backgroundImage: $backgroundImage, links: $links, followerCount: $followerCount, followingCount: $followingCount, feedCount: $feedCount, postCount: $postCount, isFollowing: $isFollowing, isBlocking: $isBlocking, albums: $albums)';
}

/// OpenAPI codec converting between [UserProfileResponse] and a JSON object.
class _Codec extends OpenApiCodec<UserProfileResponse, Map<String, dynamic>> {
  const new();

  @override
  UserProfileResponse decode(Map<String, dynamic> obj) => .new(
    id: obj.decode<String>('id')!,
    name: obj.decode<String>('name')!,
    image: obj.decode<String>('image'),
    url: obj.decode<String>('url')!,
    isBlocked: obj.decode<bool>('isBlocked')!,
    description: obj.decode<String>('description')!,
    backgroundImage: obj.decode<String>('backgroundImage'),
    links: obj.decode<List<LinkResponse>>('links')!,
    followerCount: obj.decode<num>('followerCount')!,
    followingCount: obj.decode<num>('followingCount')!,
    feedCount: obj.decode<num>('feedCount')!,
    postCount: obj.decode<num>('postCount')!,
    isFollowing: obj.decode<bool>('isFollowing')!,
    isBlocking: obj.decode<bool>('isBlocking')!,
    albums: obj.decode<List<AlbumWithCountResponse>>('albums')!,
  );

  @override
  Map<String, dynamic> encode(UserProfileResponse value) => {
    'id': value.id.encode(),
    'name': value.name.encode(),
    'image': value.image?.encode(),
    'url': value.url.encode(),
    'isBlocked': value.isBlocked.encode(),
    'description': value.description.encode(),
    'backgroundImage': value.backgroundImage?.encode(),
    'links': value.links.encode(),
    'followerCount': value.followerCount.encode(),
    'followingCount': value.followingCount.encode(),
    'feedCount': value.feedCount.encode(),
    'postCount': value.postCount.encode(),
    'isFollowing': value.isFollowing.encode(),
    'isBlocking': value.isBlocking.encode(),
    'albums': value.albums.encode(),
  };
}
