// Generated by Pervice OpenAPI Generator on October 8, 2026
// Do not edit this file manually.

// ignore_for_file: unused_import
import 'package:pervice_openapi/pervice_openapi.dart';

import '../api.dart';

/// Model representing the VerifyIdentityRequest schema.
final class VerifyIdentityRequest {
  const new({
    required this.identityVerificationId,
  });

  final String identityVerificationId;

  /// OpenAPI codec for encoding and decoding [VerifyIdentityRequest].
  static const codec = _Codec();
}

/// OpenAPI codec converting between [VerifyIdentityRequest] and a JSON object.
class _Codec extends OpenApiCodec<VerifyIdentityRequest, Map<String, dynamic>> {
  const new();

  @override
  VerifyIdentityRequest decode(Map<String, dynamic> obj) => .new(
    identityVerificationId: obj.decode<String>('identityVerificationId')!,
  );

  @override
  Map<String, dynamic> encode(VerifyIdentityRequest value) => {
    'identityVerificationId': value.identityVerificationId.encode(),
  };
}
